// Code generated by protoc-gen-go. DO NOT EDIT.
// source: identity.proto

package identity_proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type StartSignInReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StartSignInReq) Reset()         { *m = StartSignInReq{} }
func (m *StartSignInReq) String() string { return proto.CompactTextString(m) }
func (*StartSignInReq) ProtoMessage()    {}
func (*StartSignInReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_identity_30fb4ee92ce8cf34, []int{0}
}
func (m *StartSignInReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartSignInReq.Unmarshal(m, b)
}
func (m *StartSignInReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartSignInReq.Marshal(b, m, deterministic)
}
func (dst *StartSignInReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartSignInReq.Merge(dst, src)
}
func (m *StartSignInReq) XXX_Size() int {
	return xxx_messageInfo_StartSignInReq.Size(m)
}
func (m *StartSignInReq) XXX_DiscardUnknown() {
	xxx_messageInfo_StartSignInReq.DiscardUnknown(m)
}

var xxx_messageInfo_StartSignInReq proto.InternalMessageInfo

type StartSignUpReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StartSignUpReq) Reset()         { *m = StartSignUpReq{} }
func (m *StartSignUpReq) String() string { return proto.CompactTextString(m) }
func (*StartSignUpReq) ProtoMessage()    {}
func (*StartSignUpReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_identity_30fb4ee92ce8cf34, []int{1}
}
func (m *StartSignUpReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartSignUpReq.Unmarshal(m, b)
}
func (m *StartSignUpReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartSignUpReq.Marshal(b, m, deterministic)
}
func (dst *StartSignUpReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartSignUpReq.Merge(dst, src)
}
func (m *StartSignUpReq) XXX_Size() int {
	return xxx_messageInfo_StartSignUpReq.Size(m)
}
func (m *StartSignUpReq) XXX_DiscardUnknown() {
	xxx_messageInfo_StartSignUpReq.DiscardUnknown(m)
}

var xxx_messageInfo_StartSignUpReq proto.InternalMessageInfo

type StartAttachReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StartAttachReq) Reset()         { *m = StartAttachReq{} }
func (m *StartAttachReq) String() string { return proto.CompactTextString(m) }
func (*StartAttachReq) ProtoMessage()    {}
func (*StartAttachReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_identity_30fb4ee92ce8cf34, []int{2}
}
func (m *StartAttachReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartAttachReq.Unmarshal(m, b)
}
func (m *StartAttachReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartAttachReq.Marshal(b, m, deterministic)
}
func (dst *StartAttachReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartAttachReq.Merge(dst, src)
}
func (m *StartAttachReq) XXX_Size() int {
	return xxx_messageInfo_StartAttachReq.Size(m)
}
func (m *StartAttachReq) XXX_DiscardUnknown() {
	xxx_messageInfo_StartAttachReq.DiscardUnknown(m)
}

var xxx_messageInfo_StartAttachReq proto.InternalMessageInfo

// // ListMessages
type ListSupportedIdentitiesAndVerifiersReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListSupportedIdentitiesAndVerifiersReq) Reset() {
	*m = ListSupportedIdentitiesAndVerifiersReq{}
}
func (m *ListSupportedIdentitiesAndVerifiersReq) String() string { return proto.CompactTextString(m) }
func (*ListSupportedIdentitiesAndVerifiersReq) ProtoMessage()    {}
func (*ListSupportedIdentitiesAndVerifiersReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_identity_30fb4ee92ce8cf34, []int{3}
}
func (m *ListSupportedIdentitiesAndVerifiersReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListSupportedIdentitiesAndVerifiersReq.Unmarshal(m, b)
}
func (m *ListSupportedIdentitiesAndVerifiersReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListSupportedIdentitiesAndVerifiersReq.Marshal(b, m, deterministic)
}
func (dst *ListSupportedIdentitiesAndVerifiersReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListSupportedIdentitiesAndVerifiersReq.Merge(dst, src)
}
func (m *ListSupportedIdentitiesAndVerifiersReq) XXX_Size() int {
	return xxx_messageInfo_ListSupportedIdentitiesAndVerifiersReq.Size(m)
}
func (m *ListSupportedIdentitiesAndVerifiersReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ListSupportedIdentitiesAndVerifiersReq.DiscardUnknown(m)
}

var xxx_messageInfo_ListSupportedIdentitiesAndVerifiersReq proto.InternalMessageInfo

type ListMyIdentitiesAndVerifiersReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListMyIdentitiesAndVerifiersReq) Reset()         { *m = ListMyIdentitiesAndVerifiersReq{} }
func (m *ListMyIdentitiesAndVerifiersReq) String() string { return proto.CompactTextString(m) }
func (*ListMyIdentitiesAndVerifiersReq) ProtoMessage()    {}
func (*ListMyIdentitiesAndVerifiersReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_identity_30fb4ee92ce8cf34, []int{4}
}
func (m *ListMyIdentitiesAndVerifiersReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListMyIdentitiesAndVerifiersReq.Unmarshal(m, b)
}
func (m *ListMyIdentitiesAndVerifiersReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListMyIdentitiesAndVerifiersReq.Marshal(b, m, deterministic)
}
func (dst *ListMyIdentitiesAndVerifiersReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListMyIdentitiesAndVerifiersReq.Merge(dst, src)
}
func (m *ListMyIdentitiesAndVerifiersReq) XXX_Size() int {
	return xxx_messageInfo_ListMyIdentitiesAndVerifiersReq.Size(m)
}
func (m *ListMyIdentitiesAndVerifiersReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ListMyIdentitiesAndVerifiersReq.DiscardUnknown(m)
}

var xxx_messageInfo_ListMyIdentitiesAndVerifiersReq proto.InternalMessageInfo

type VerifierDetailsResp struct {
	IdentitiyNames       []string           `protobuf:"bytes,1,rep,name=IdentitiyNames,proto3" json:"IdentitiyNames,omitempty"`
	Verifiers            []*VerifierDetails `protobuf:"bytes,2,rep,name=Verifiers,proto3" json:"Verifiers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *VerifierDetailsResp) Reset()         { *m = VerifierDetailsResp{} }
func (m *VerifierDetailsResp) String() string { return proto.CompactTextString(m) }
func (*VerifierDetailsResp) ProtoMessage()    {}
func (*VerifierDetailsResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_identity_30fb4ee92ce8cf34, []int{5}
}
func (m *VerifierDetailsResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifierDetailsResp.Unmarshal(m, b)
}
func (m *VerifierDetailsResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifierDetailsResp.Marshal(b, m, deterministic)
}
func (dst *VerifierDetailsResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifierDetailsResp.Merge(dst, src)
}
func (m *VerifierDetailsResp) XXX_Size() int {
	return xxx_messageInfo_VerifierDetailsResp.Size(m)
}
func (m *VerifierDetailsResp) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifierDetailsResp.DiscardUnknown(m)
}

var xxx_messageInfo_VerifierDetailsResp proto.InternalMessageInfo

func (m *VerifierDetailsResp) GetIdentitiyNames() []string {
	if m != nil {
		return m.IdentitiyNames
	}
	return nil
}

func (m *VerifierDetailsResp) GetVerifiers() []*VerifierDetails {
	if m != nil {
		return m.Verifiers
	}
	return nil
}

type VerifierDetails struct {
	Name                 string   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	IdentityName         string   `protobuf:"bytes,2,opt,name=IdentityName,proto3" json:"IdentityName,omitempty"`
	SupportRegular       bool     `protobuf:"varint,3,opt,name=SupportRegular,proto3" json:"SupportRegular,omitempty"`
	SupportReverse       bool     `protobuf:"varint,4,opt,name=SupportReverse,proto3" json:"SupportReverse,omitempty"`
	SupportOAuth2        bool     `protobuf:"varint,5,opt,name=SupportOAuth2,proto3" json:"SupportOAuth2,omitempty"`
	SupportStatic        bool     `protobuf:"varint,6,opt,name=SupportStatic,proto3" json:"SupportStatic,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VerifierDetails) Reset()         { *m = VerifierDetails{} }
func (m *VerifierDetails) String() string { return proto.CompactTextString(m) }
func (*VerifierDetails) ProtoMessage()    {}
func (*VerifierDetails) Descriptor() ([]byte, []int) {
	return fileDescriptor_identity_30fb4ee92ce8cf34, []int{6}
}
func (m *VerifierDetails) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifierDetails.Unmarshal(m, b)
}
func (m *VerifierDetails) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifierDetails.Marshal(b, m, deterministic)
}
func (dst *VerifierDetails) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifierDetails.Merge(dst, src)
}
func (m *VerifierDetails) XXX_Size() int {
	return xxx_messageInfo_VerifierDetails.Size(m)
}
func (m *VerifierDetails) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifierDetails.DiscardUnknown(m)
}

var xxx_messageInfo_VerifierDetails proto.InternalMessageInfo

func (m *VerifierDetails) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *VerifierDetails) GetIdentityName() string {
	if m != nil {
		return m.IdentityName
	}
	return ""
}

func (m *VerifierDetails) GetSupportRegular() bool {
	if m != nil {
		return m.SupportRegular
	}
	return false
}

func (m *VerifierDetails) GetSupportReverse() bool {
	if m != nil {
		return m.SupportReverse
	}
	return false
}

func (m *VerifierDetails) GetSupportOAuth2() bool {
	if m != nil {
		return m.SupportOAuth2
	}
	return false
}

func (m *VerifierDetails) GetSupportStatic() bool {
	if m != nil {
		return m.SupportStatic
	}
	return false
}

type ListMyIdentitiesAndVerifiersResp struct {
	Identities           []*IdentityData `protobuf:"bytes,1,rep,name=Identities,proto3" json:"Identities,omitempty"`
	Verifiers            []string        `protobuf:"bytes,2,rep,name=Verifiers,proto3" json:"Verifiers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ListMyIdentitiesAndVerifiersResp) Reset()         { *m = ListMyIdentitiesAndVerifiersResp{} }
func (m *ListMyIdentitiesAndVerifiersResp) String() string { return proto.CompactTextString(m) }
func (*ListMyIdentitiesAndVerifiersResp) ProtoMessage()    {}
func (*ListMyIdentitiesAndVerifiersResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_identity_30fb4ee92ce8cf34, []int{7}
}
func (m *ListMyIdentitiesAndVerifiersResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListMyIdentitiesAndVerifiersResp.Unmarshal(m, b)
}
func (m *ListMyIdentitiesAndVerifiersResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListMyIdentitiesAndVerifiersResp.Marshal(b, m, deterministic)
}
func (dst *ListMyIdentitiesAndVerifiersResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListMyIdentitiesAndVerifiersResp.Merge(dst, src)
}
func (m *ListMyIdentitiesAndVerifiersResp) XXX_Size() int {
	return xxx_messageInfo_ListMyIdentitiesAndVerifiersResp.Size(m)
}
func (m *ListMyIdentitiesAndVerifiersResp) XXX_DiscardUnknown() {
	xxx_messageInfo_ListMyIdentitiesAndVerifiersResp.DiscardUnknown(m)
}

var xxx_messageInfo_ListMyIdentitiesAndVerifiersResp proto.InternalMessageInfo

func (m *ListMyIdentitiesAndVerifiersResp) GetIdentities() []*IdentityData {
	if m != nil {
		return m.Identities
	}
	return nil
}

func (m *ListMyIdentitiesAndVerifiersResp) GetVerifiers() []string {
	if m != nil {
		return m.Verifiers
	}
	return nil
}

type IdentityData struct {
	Name                 string   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Identity             string   `protobuf:"bytes,2,opt,name=Identity,proto3" json:"Identity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IdentityData) Reset()         { *m = IdentityData{} }
func (m *IdentityData) String() string { return proto.CompactTextString(m) }
func (*IdentityData) ProtoMessage()    {}
func (*IdentityData) Descriptor() ([]byte, []int) {
	return fileDescriptor_identity_30fb4ee92ce8cf34, []int{8}
}
func (m *IdentityData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IdentityData.Unmarshal(m, b)
}
func (m *IdentityData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IdentityData.Marshal(b, m, deterministic)
}
func (dst *IdentityData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IdentityData.Merge(dst, src)
}
func (m *IdentityData) XXX_Size() int {
	return xxx_messageInfo_IdentityData.Size(m)
}
func (m *IdentityData) XXX_DiscardUnknown() {
	xxx_messageInfo_IdentityData.DiscardUnknown(m)
}

var xxx_messageInfo_IdentityData proto.InternalMessageInfo

func (m *IdentityData) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *IdentityData) GetIdentity() string {
	if m != nil {
		return m.Identity
	}
	return ""
}

type StartReq struct {
	VerifierName         string            `protobuf:"bytes,1,opt,name=VerifierName,proto3" json:"VerifierName,omitempty"`
	IdentityName         string            `protobuf:"bytes,2,opt,name=IdentityName,proto3" json:"IdentityName,omitempty"`
	Identity             string            `protobuf:"bytes,3,opt,name=Identity,proto3" json:"Identity,omitempty"`
	Args                 map[string]string `protobuf:"bytes,4,rep,name=Args,proto3" json:"Args,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *StartReq) Reset()         { *m = StartReq{} }
func (m *StartReq) String() string { return proto.CompactTextString(m) }
func (*StartReq) ProtoMessage()    {}
func (*StartReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_identity_30fb4ee92ce8cf34, []int{9}
}
func (m *StartReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartReq.Unmarshal(m, b)
}
func (m *StartReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartReq.Marshal(b, m, deterministic)
}
func (dst *StartReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartReq.Merge(dst, src)
}
func (m *StartReq) XXX_Size() int {
	return xxx_messageInfo_StartReq.Size(m)
}
func (m *StartReq) XXX_DiscardUnknown() {
	xxx_messageInfo_StartReq.DiscardUnknown(m)
}

var xxx_messageInfo_StartReq proto.InternalMessageInfo

func (m *StartReq) GetVerifierName() string {
	if m != nil {
		return m.VerifierName
	}
	return ""
}

func (m *StartReq) GetIdentityName() string {
	if m != nil {
		return m.IdentityName
	}
	return ""
}

func (m *StartReq) GetIdentity() string {
	if m != nil {
		return m.Identity
	}
	return ""
}

func (m *StartReq) GetArgs() map[string]string {
	if m != nil {
		return m.Args
	}
	return nil
}

type StartResp struct {
	Directions           map[string]string `protobuf:"bytes,3,rep,name=Directions,proto3" json:"Directions,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *StartResp) Reset()         { *m = StartResp{} }
func (m *StartResp) String() string { return proto.CompactTextString(m) }
func (*StartResp) ProtoMessage()    {}
func (*StartResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_identity_30fb4ee92ce8cf34, []int{10}
}
func (m *StartResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartResp.Unmarshal(m, b)
}
func (m *StartResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartResp.Marshal(b, m, deterministic)
}
func (dst *StartResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartResp.Merge(dst, src)
}
func (m *StartResp) XXX_Size() int {
	return xxx_messageInfo_StartResp.Size(m)
}
func (m *StartResp) XXX_DiscardUnknown() {
	xxx_messageInfo_StartResp.DiscardUnknown(m)
}

var xxx_messageInfo_StartResp proto.InternalMessageInfo

func (m *StartResp) GetDirections() map[string]string {
	if m != nil {
		return m.Directions
	}
	return nil
}

type StatusReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StatusReq) Reset()         { *m = StatusReq{} }
func (m *StatusReq) String() string { return proto.CompactTextString(m) }
func (*StatusReq) ProtoMessage()    {}
func (*StatusReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_identity_30fb4ee92ce8cf34, []int{11}
}
func (m *StatusReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatusReq.Unmarshal(m, b)
}
func (m *StatusReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatusReq.Marshal(b, m, deterministic)
}
func (dst *StatusReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatusReq.Merge(dst, src)
}
func (m *StatusReq) XXX_Size() int {
	return xxx_messageInfo_StatusReq.Size(m)
}
func (m *StatusReq) XXX_DiscardUnknown() {
	xxx_messageInfo_StatusReq.DiscardUnknown(m)
}

var xxx_messageInfo_StatusReq proto.InternalMessageInfo

type Status struct {
	Token                string                `protobuf:"bytes,1,opt,name=Token,proto3" json:"Token,omitempty"`
	Authenticating       *StatusAuthenticating `protobuf:"bytes,2,opt,name=Authenticating,proto3" json:"Authenticating,omitempty"`
	Authenticated        *StatusAuthenticated  `protobuf:"bytes,3,opt,name=Authenticated,proto3" json:"Authenticated,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *Status) Reset()         { *m = Status{} }
func (m *Status) String() string { return proto.CompactTextString(m) }
func (*Status) ProtoMessage()    {}
func (*Status) Descriptor() ([]byte, []int) {
	return fileDescriptor_identity_30fb4ee92ce8cf34, []int{12}
}
func (m *Status) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Status.Unmarshal(m, b)
}
func (m *Status) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Status.Marshal(b, m, deterministic)
}
func (dst *Status) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Status.Merge(dst, src)
}
func (m *Status) XXX_Size() int {
	return xxx_messageInfo_Status.Size(m)
}
func (m *Status) XXX_DiscardUnknown() {
	xxx_messageInfo_Status.DiscardUnknown(m)
}

var xxx_messageInfo_Status proto.InternalMessageInfo

func (m *Status) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *Status) GetAuthenticating() *StatusAuthenticating {
	if m != nil {
		return m.Authenticating
	}
	return nil
}

func (m *Status) GetAuthenticated() *StatusAuthenticated {
	if m != nil {
		return m.Authenticated
	}
	return nil
}

type StatusAuthenticated struct {
	User                 string   `protobuf:"bytes,1,opt,name=User,proto3" json:"User,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StatusAuthenticated) Reset()         { *m = StatusAuthenticated{} }
func (m *StatusAuthenticated) String() string { return proto.CompactTextString(m) }
func (*StatusAuthenticated) ProtoMessage()    {}
func (*StatusAuthenticated) Descriptor() ([]byte, []int) {
	return fileDescriptor_identity_30fb4ee92ce8cf34, []int{13}
}
func (m *StatusAuthenticated) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatusAuthenticated.Unmarshal(m, b)
}
func (m *StatusAuthenticated) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatusAuthenticated.Marshal(b, m, deterministic)
}
func (dst *StatusAuthenticated) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatusAuthenticated.Merge(dst, src)
}
func (m *StatusAuthenticated) XXX_Size() int {
	return xxx_messageInfo_StatusAuthenticated.Size(m)
}
func (m *StatusAuthenticated) XXX_DiscardUnknown() {
	xxx_messageInfo_StatusAuthenticated.DiscardUnknown(m)
}

var xxx_messageInfo_StatusAuthenticated proto.InternalMessageInfo

func (m *StatusAuthenticated) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

type StatusAuthenticating struct {
	// Types that are valid to be assigned to Objective:
	//	*StatusAuthenticating_SignIn
	//	*StatusAuthenticating_SignUp
	//	*StatusAuthenticating_Attach
	Objective            isStatusAuthenticating_Objective `protobuf_oneof:"Objective"`
	CompletedFactors     []*StatusCompletedFactors        `protobuf:"bytes,4,rep,name=CompletedFactors,proto3" json:"CompletedFactors,omitempty"`
	RemainingFactors     int64                            `protobuf:"varint,5,opt,name=RemainingFactors,proto3" json:"RemainingFactors,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                         `json:"-"`
	XXX_unrecognized     []byte                           `json:"-"`
	XXX_sizecache        int32                            `json:"-"`
}

func (m *StatusAuthenticating) Reset()         { *m = StatusAuthenticating{} }
func (m *StatusAuthenticating) String() string { return proto.CompactTextString(m) }
func (*StatusAuthenticating) ProtoMessage()    {}
func (*StatusAuthenticating) Descriptor() ([]byte, []int) {
	return fileDescriptor_identity_30fb4ee92ce8cf34, []int{14}
}
func (m *StatusAuthenticating) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatusAuthenticating.Unmarshal(m, b)
}
func (m *StatusAuthenticating) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatusAuthenticating.Marshal(b, m, deterministic)
}
func (dst *StatusAuthenticating) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatusAuthenticating.Merge(dst, src)
}
func (m *StatusAuthenticating) XXX_Size() int {
	return xxx_messageInfo_StatusAuthenticating.Size(m)
}
func (m *StatusAuthenticating) XXX_DiscardUnknown() {
	xxx_messageInfo_StatusAuthenticating.DiscardUnknown(m)
}

var xxx_messageInfo_StatusAuthenticating proto.InternalMessageInfo

type isStatusAuthenticating_Objective interface {
	isStatusAuthenticating_Objective()
}

type StatusAuthenticating_SignIn struct {
	SignIn bool `protobuf:"varint,1,opt,name=SignIn,proto3,oneof"`
}
type StatusAuthenticating_SignUp struct {
	SignUp bool `protobuf:"varint,2,opt,name=SignUp,proto3,oneof"`
}
type StatusAuthenticating_Attach struct {
	Attach bool `protobuf:"varint,3,opt,name=Attach,proto3,oneof"`
}

func (*StatusAuthenticating_SignIn) isStatusAuthenticating_Objective() {}
func (*StatusAuthenticating_SignUp) isStatusAuthenticating_Objective() {}
func (*StatusAuthenticating_Attach) isStatusAuthenticating_Objective() {}

func (m *StatusAuthenticating) GetObjective() isStatusAuthenticating_Objective {
	if m != nil {
		return m.Objective
	}
	return nil
}

func (m *StatusAuthenticating) GetSignIn() bool {
	if x, ok := m.GetObjective().(*StatusAuthenticating_SignIn); ok {
		return x.SignIn
	}
	return false
}

func (m *StatusAuthenticating) GetSignUp() bool {
	if x, ok := m.GetObjective().(*StatusAuthenticating_SignUp); ok {
		return x.SignUp
	}
	return false
}

func (m *StatusAuthenticating) GetAttach() bool {
	if x, ok := m.GetObjective().(*StatusAuthenticating_Attach); ok {
		return x.Attach
	}
	return false
}

func (m *StatusAuthenticating) GetCompletedFactors() []*StatusCompletedFactors {
	if m != nil {
		return m.CompletedFactors
	}
	return nil
}

func (m *StatusAuthenticating) GetRemainingFactors() int64 {
	if m != nil {
		return m.RemainingFactors
	}
	return 0
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*StatusAuthenticating) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _StatusAuthenticating_OneofMarshaler, _StatusAuthenticating_OneofUnmarshaler, _StatusAuthenticating_OneofSizer, []interface{}{
		(*StatusAuthenticating_SignIn)(nil),
		(*StatusAuthenticating_SignUp)(nil),
		(*StatusAuthenticating_Attach)(nil),
	}
}

func _StatusAuthenticating_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*StatusAuthenticating)
	// Objective
	switch x := m.Objective.(type) {
	case *StatusAuthenticating_SignIn:
		t := uint64(0)
		if x.SignIn {
			t = 1
		}
		b.EncodeVarint(1<<3 | proto.WireVarint)
		b.EncodeVarint(t)
	case *StatusAuthenticating_SignUp:
		t := uint64(0)
		if x.SignUp {
			t = 1
		}
		b.EncodeVarint(2<<3 | proto.WireVarint)
		b.EncodeVarint(t)
	case *StatusAuthenticating_Attach:
		t := uint64(0)
		if x.Attach {
			t = 1
		}
		b.EncodeVarint(3<<3 | proto.WireVarint)
		b.EncodeVarint(t)
	case nil:
	default:
		return fmt.Errorf("StatusAuthenticating.Objective has unexpected type %T", x)
	}
	return nil
}

func _StatusAuthenticating_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*StatusAuthenticating)
	switch tag {
	case 1: // Objective.SignIn
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.Objective = &StatusAuthenticating_SignIn{x != 0}
		return true, err
	case 2: // Objective.SignUp
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.Objective = &StatusAuthenticating_SignUp{x != 0}
		return true, err
	case 3: // Objective.Attach
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.Objective = &StatusAuthenticating_Attach{x != 0}
		return true, err
	default:
		return false, nil
	}
}

func _StatusAuthenticating_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*StatusAuthenticating)
	// Objective
	switch x := m.Objective.(type) {
	case *StatusAuthenticating_SignIn:
		n += 1 // tag and wire
		n += 1
	case *StatusAuthenticating_SignUp:
		n += 1 // tag and wire
		n += 1
	case *StatusAuthenticating_Attach:
		n += 1 // tag and wire
		n += 1
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type StatusCompletedFactors struct {
	VerifierName         string   `protobuf:"bytes,1,opt,name=VerifierName,proto3" json:"VerifierName,omitempty"`
	IdentityName         string   `protobuf:"bytes,2,opt,name=IdentityName,proto3" json:"IdentityName,omitempty"`
	Identity             string   `protobuf:"bytes,3,opt,name=Identity,proto3" json:"Identity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StatusCompletedFactors) Reset()         { *m = StatusCompletedFactors{} }
func (m *StatusCompletedFactors) String() string { return proto.CompactTextString(m) }
func (*StatusCompletedFactors) ProtoMessage()    {}
func (*StatusCompletedFactors) Descriptor() ([]byte, []int) {
	return fileDescriptor_identity_30fb4ee92ce8cf34, []int{15}
}
func (m *StatusCompletedFactors) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatusCompletedFactors.Unmarshal(m, b)
}
func (m *StatusCompletedFactors) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatusCompletedFactors.Marshal(b, m, deterministic)
}
func (dst *StatusCompletedFactors) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatusCompletedFactors.Merge(dst, src)
}
func (m *StatusCompletedFactors) XXX_Size() int {
	return xxx_messageInfo_StatusCompletedFactors.Size(m)
}
func (m *StatusCompletedFactors) XXX_DiscardUnknown() {
	xxx_messageInfo_StatusCompletedFactors.DiscardUnknown(m)
}

var xxx_messageInfo_StatusCompletedFactors proto.InternalMessageInfo

func (m *StatusCompletedFactors) GetVerifierName() string {
	if m != nil {
		return m.VerifierName
	}
	return ""
}

func (m *StatusCompletedFactors) GetIdentityName() string {
	if m != nil {
		return m.IdentityName
	}
	return ""
}

func (m *StatusCompletedFactors) GetIdentity() string {
	if m != nil {
		return m.Identity
	}
	return ""
}

type UserMergeReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserMergeReq) Reset()         { *m = UserMergeReq{} }
func (m *UserMergeReq) String() string { return proto.CompactTextString(m) }
func (*UserMergeReq) ProtoMessage()    {}
func (*UserMergeReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_identity_30fb4ee92ce8cf34, []int{16}
}
func (m *UserMergeReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserMergeReq.Unmarshal(m, b)
}
func (m *UserMergeReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserMergeReq.Marshal(b, m, deterministic)
}
func (dst *UserMergeReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserMergeReq.Merge(dst, src)
}
func (m *UserMergeReq) XXX_Size() int {
	return xxx_messageInfo_UserMergeReq.Size(m)
}
func (m *UserMergeReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UserMergeReq.DiscardUnknown(m)
}

var xxx_messageInfo_UserMergeReq proto.InternalMessageInfo

type UserMergeResp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserMergeResp) Reset()         { *m = UserMergeResp{} }
func (m *UserMergeResp) String() string { return proto.CompactTextString(m) }
func (*UserMergeResp) ProtoMessage()    {}
func (*UserMergeResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_identity_30fb4ee92ce8cf34, []int{17}
}
func (m *UserMergeResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserMergeResp.Unmarshal(m, b)
}
func (m *UserMergeResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserMergeResp.Marshal(b, m, deterministic)
}
func (dst *UserMergeResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserMergeResp.Merge(dst, src)
}
func (m *UserMergeResp) XXX_Size() int {
	return xxx_messageInfo_UserMergeResp.Size(m)
}
func (m *UserMergeResp) XXX_DiscardUnknown() {
	xxx_messageInfo_UserMergeResp.DiscardUnknown(m)
}

var xxx_messageInfo_UserMergeResp proto.InternalMessageInfo

type CancelAuthenticationReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CancelAuthenticationReq) Reset()         { *m = CancelAuthenticationReq{} }
func (m *CancelAuthenticationReq) String() string { return proto.CompactTextString(m) }
func (*CancelAuthenticationReq) ProtoMessage()    {}
func (*CancelAuthenticationReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_identity_30fb4ee92ce8cf34, []int{18}
}
func (m *CancelAuthenticationReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CancelAuthenticationReq.Unmarshal(m, b)
}
func (m *CancelAuthenticationReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CancelAuthenticationReq.Marshal(b, m, deterministic)
}
func (dst *CancelAuthenticationReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CancelAuthenticationReq.Merge(dst, src)
}
func (m *CancelAuthenticationReq) XXX_Size() int {
	return xxx_messageInfo_CancelAuthenticationReq.Size(m)
}
func (m *CancelAuthenticationReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CancelAuthenticationReq.DiscardUnknown(m)
}

var xxx_messageInfo_CancelAuthenticationReq proto.InternalMessageInfo

type LogoutReq struct {
	AllSessions          bool     `protobuf:"varint,1,opt,name=AllSessions,proto3" json:"AllSessions,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogoutReq) Reset()         { *m = LogoutReq{} }
func (m *LogoutReq) String() string { return proto.CompactTextString(m) }
func (*LogoutReq) ProtoMessage()    {}
func (*LogoutReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_identity_30fb4ee92ce8cf34, []int{19}
}
func (m *LogoutReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogoutReq.Unmarshal(m, b)
}
func (m *LogoutReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogoutReq.Marshal(b, m, deterministic)
}
func (dst *LogoutReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogoutReq.Merge(dst, src)
}
func (m *LogoutReq) XXX_Size() int {
	return xxx_messageInfo_LogoutReq.Size(m)
}
func (m *LogoutReq) XXX_DiscardUnknown() {
	xxx_messageInfo_LogoutReq.DiscardUnknown(m)
}

var xxx_messageInfo_LogoutReq proto.InternalMessageInfo

func (m *LogoutReq) GetAllSessions() bool {
	if m != nil {
		return m.AllSessions
	}
	return false
}

type InitializeStaticVerifierReq struct {
	VerifierName         string            `protobuf:"bytes,1,opt,name=VerifierName,proto3" json:"VerifierName,omitempty"`
	Args                 map[string]string `protobuf:"bytes,2,rep,name=Args,proto3" json:"Args,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *InitializeStaticVerifierReq) Reset()         { *m = InitializeStaticVerifierReq{} }
func (m *InitializeStaticVerifierReq) String() string { return proto.CompactTextString(m) }
func (*InitializeStaticVerifierReq) ProtoMessage()    {}
func (*InitializeStaticVerifierReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_identity_30fb4ee92ce8cf34, []int{20}
}
func (m *InitializeStaticVerifierReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InitializeStaticVerifierReq.Unmarshal(m, b)
}
func (m *InitializeStaticVerifierReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InitializeStaticVerifierReq.Marshal(b, m, deterministic)
}
func (dst *InitializeStaticVerifierReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InitializeStaticVerifierReq.Merge(dst, src)
}
func (m *InitializeStaticVerifierReq) XXX_Size() int {
	return xxx_messageInfo_InitializeStaticVerifierReq.Size(m)
}
func (m *InitializeStaticVerifierReq) XXX_DiscardUnknown() {
	xxx_messageInfo_InitializeStaticVerifierReq.DiscardUnknown(m)
}

var xxx_messageInfo_InitializeStaticVerifierReq proto.InternalMessageInfo

func (m *InitializeStaticVerifierReq) GetVerifierName() string {
	if m != nil {
		return m.VerifierName
	}
	return ""
}

func (m *InitializeStaticVerifierReq) GetArgs() map[string]string {
	if m != nil {
		return m.Args
	}
	return nil
}

type InitializeStaticVerifierResp struct {
	Result               map[string]string `protobuf:"bytes,1,rep,name=Result,proto3" json:"Result,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *InitializeStaticVerifierResp) Reset()         { *m = InitializeStaticVerifierResp{} }
func (m *InitializeStaticVerifierResp) String() string { return proto.CompactTextString(m) }
func (*InitializeStaticVerifierResp) ProtoMessage()    {}
func (*InitializeStaticVerifierResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_identity_30fb4ee92ce8cf34, []int{21}
}
func (m *InitializeStaticVerifierResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InitializeStaticVerifierResp.Unmarshal(m, b)
}
func (m *InitializeStaticVerifierResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InitializeStaticVerifierResp.Marshal(b, m, deterministic)
}
func (dst *InitializeStaticVerifierResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InitializeStaticVerifierResp.Merge(dst, src)
}
func (m *InitializeStaticVerifierResp) XXX_Size() int {
	return xxx_messageInfo_InitializeStaticVerifierResp.Size(m)
}
func (m *InitializeStaticVerifierResp) XXX_DiscardUnknown() {
	xxx_messageInfo_InitializeStaticVerifierResp.DiscardUnknown(m)
}

var xxx_messageInfo_InitializeStaticVerifierResp proto.InternalMessageInfo

func (m *InitializeStaticVerifierResp) GetResult() map[string]string {
	if m != nil {
		return m.Result
	}
	return nil
}

type VerifyReq struct {
	VerifierName         string   `protobuf:"bytes,1,opt,name=VerifierName,proto3" json:"VerifierName,omitempty"`
	VerificationCode     string   `protobuf:"bytes,2,opt,name=VerificationCode,proto3" json:"VerificationCode,omitempty"`
	IdentityName         string   `protobuf:"bytes,3,opt,name=IdentityName,proto3" json:"IdentityName,omitempty"`
	Identity             string   `protobuf:"bytes,4,opt,name=Identity,proto3" json:"Identity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VerifyReq) Reset()         { *m = VerifyReq{} }
func (m *VerifyReq) String() string { return proto.CompactTextString(m) }
func (*VerifyReq) ProtoMessage()    {}
func (*VerifyReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_identity_30fb4ee92ce8cf34, []int{22}
}
func (m *VerifyReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyReq.Unmarshal(m, b)
}
func (m *VerifyReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyReq.Marshal(b, m, deterministic)
}
func (dst *VerifyReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyReq.Merge(dst, src)
}
func (m *VerifyReq) XXX_Size() int {
	return xxx_messageInfo_VerifyReq.Size(m)
}
func (m *VerifyReq) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyReq.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyReq proto.InternalMessageInfo

func (m *VerifyReq) GetVerifierName() string {
	if m != nil {
		return m.VerifierName
	}
	return ""
}

func (m *VerifyReq) GetVerificationCode() string {
	if m != nil {
		return m.VerificationCode
	}
	return ""
}

func (m *VerifyReq) GetIdentityName() string {
	if m != nil {
		return m.IdentityName
	}
	return ""
}

func (m *VerifyReq) GetIdentity() string {
	if m != nil {
		return m.Identity
	}
	return ""
}

type LoginAsReq struct {
	User                 string   `protobuf:"bytes,1,opt,name=User,proto3" json:"User,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginAsReq) Reset()         { *m = LoginAsReq{} }
func (m *LoginAsReq) String() string { return proto.CompactTextString(m) }
func (*LoginAsReq) ProtoMessage()    {}
func (*LoginAsReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_identity_30fb4ee92ce8cf34, []int{23}
}
func (m *LoginAsReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginAsReq.Unmarshal(m, b)
}
func (m *LoginAsReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginAsReq.Marshal(b, m, deterministic)
}
func (dst *LoginAsReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginAsReq.Merge(dst, src)
}
func (m *LoginAsReq) XXX_Size() int {
	return xxx_messageInfo_LoginAsReq.Size(m)
}
func (m *LoginAsReq) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginAsReq.DiscardUnknown(m)
}

var xxx_messageInfo_LoginAsReq proto.InternalMessageInfo

func (m *LoginAsReq) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

type LoginAsResp struct {
	Session              string   `protobuf:"bytes,1,opt,name=Session,proto3" json:"Session,omitempty"`
	User                 string   `protobuf:"bytes,2,opt,name=User,proto3" json:"User,omitempty"`
	Error                string   `protobuf:"bytes,3,opt,name=Error,proto3" json:"Error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginAsResp) Reset()         { *m = LoginAsResp{} }
func (m *LoginAsResp) String() string { return proto.CompactTextString(m) }
func (*LoginAsResp) ProtoMessage()    {}
func (*LoginAsResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_identity_30fb4ee92ce8cf34, []int{24}
}
func (m *LoginAsResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginAsResp.Unmarshal(m, b)
}
func (m *LoginAsResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginAsResp.Marshal(b, m, deterministic)
}
func (dst *LoginAsResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginAsResp.Merge(dst, src)
}
func (m *LoginAsResp) XXX_Size() int {
	return xxx_messageInfo_LoginAsResp.Size(m)
}
func (m *LoginAsResp) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginAsResp.DiscardUnknown(m)
}

var xxx_messageInfo_LoginAsResp proto.InternalMessageInfo

func (m *LoginAsResp) GetSession() string {
	if m != nil {
		return m.Session
	}
	return ""
}

func (m *LoginAsResp) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *LoginAsResp) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func init() {
	proto.RegisterType((*StartSignInReq)(nil), "api.themakers.identity.StartSignInReq")
	proto.RegisterType((*StartSignUpReq)(nil), "api.themakers.identity.StartSignUpReq")
	proto.RegisterType((*StartAttachReq)(nil), "api.themakers.identity.StartAttachReq")
	proto.RegisterType((*ListSupportedIdentitiesAndVerifiersReq)(nil), "api.themakers.identity.ListSupportedIdentitiesAndVerifiersReq")
	proto.RegisterType((*ListMyIdentitiesAndVerifiersReq)(nil), "api.themakers.identity.ListMyIdentitiesAndVerifiersReq")
	proto.RegisterType((*VerifierDetailsResp)(nil), "api.themakers.identity.VerifierDetailsResp")
	proto.RegisterType((*VerifierDetails)(nil), "api.themakers.identity.VerifierDetails")
	proto.RegisterType((*ListMyIdentitiesAndVerifiersResp)(nil), "api.themakers.identity.ListMyIdentitiesAndVerifiersResp")
	proto.RegisterType((*IdentityData)(nil), "api.themakers.identity.IdentityData")
	proto.RegisterType((*StartReq)(nil), "api.themakers.identity.StartReq")
	proto.RegisterMapType((map[string]string)(nil), "api.themakers.identity.StartReq.ArgsEntry")
	proto.RegisterType((*StartResp)(nil), "api.themakers.identity.StartResp")
	proto.RegisterMapType((map[string]string)(nil), "api.themakers.identity.StartResp.DirectionsEntry")
	proto.RegisterType((*StatusReq)(nil), "api.themakers.identity.StatusReq")
	proto.RegisterType((*Status)(nil), "api.themakers.identity.Status")
	proto.RegisterType((*StatusAuthenticated)(nil), "api.themakers.identity.StatusAuthenticated")
	proto.RegisterType((*StatusAuthenticating)(nil), "api.themakers.identity.StatusAuthenticating")
	proto.RegisterType((*StatusCompletedFactors)(nil), "api.themakers.identity.StatusCompletedFactors")
	proto.RegisterType((*UserMergeReq)(nil), "api.themakers.identity.UserMergeReq")
	proto.RegisterType((*UserMergeResp)(nil), "api.themakers.identity.UserMergeResp")
	proto.RegisterType((*CancelAuthenticationReq)(nil), "api.themakers.identity.CancelAuthenticationReq")
	proto.RegisterType((*LogoutReq)(nil), "api.themakers.identity.LogoutReq")
	proto.RegisterType((*InitializeStaticVerifierReq)(nil), "api.themakers.identity.InitializeStaticVerifierReq")
	proto.RegisterMapType((map[string]string)(nil), "api.themakers.identity.InitializeStaticVerifierReq.ArgsEntry")
	proto.RegisterType((*InitializeStaticVerifierResp)(nil), "api.themakers.identity.InitializeStaticVerifierResp")
	proto.RegisterMapType((map[string]string)(nil), "api.themakers.identity.InitializeStaticVerifierResp.ResultEntry")
	proto.RegisterType((*VerifyReq)(nil), "api.themakers.identity.VerifyReq")
	proto.RegisterType((*LoginAsReq)(nil), "api.themakers.identity.LoginAsReq")
	proto.RegisterType((*LoginAsResp)(nil), "api.themakers.identity.LoginAsResp")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// IdentityClient is the client API for Identity service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type IdentityClient interface {
	ListSupportedIdentitiesAndVerifiers(ctx context.Context, in *ListSupportedIdentitiesAndVerifiersReq, opts ...grpc.CallOption) (*VerifierDetailsResp, error)
	CheckStatus(ctx context.Context, in *StatusReq, opts ...grpc.CallOption) (*Status, error)
	Logout(ctx context.Context, in *LogoutReq, opts ...grpc.CallOption) (*Status, error)
	UserMerge(ctx context.Context, in *UserMergeReq, opts ...grpc.CallOption) (*UserMergeResp, error)
	// > Only applicable to unauthenticated requests
	//  Will NOT create/modify any new user record
	//  As result of successful authentication
	//    existing user will be signed in
	StartSignIn(ctx context.Context, in *StartSignInReq, opts ...grpc.CallOption) (*Status, error)
	// > Only applicable to unauthenticated requests
	//  WILL create new user record; Can only use new (unregistered) identities
	//  As result of successful authentication
	//    new user will be created
	//    or existing user will be signed in
	StartSignUp(ctx context.Context, in *StartSignUpReq, opts ...grpc.CallOption) (*Status, error)
	// > Only applicable to authenticated requests
	//  Will add new verifier/identity to existing user
	//  As result of successful authentication
	//    new identity/verifier will be added to existing user
	StartAttach(ctx context.Context, in *StartAttachReq, opts ...grpc.CallOption) (*Status, error)
	// //////////////////////////////////////////////////////////////
	// // Working within authentication process
	//
	// This methods can be called only when there is an active authentication process
	//
	CancelAuthentication(ctx context.Context, in *CancelAuthenticationReq, opts ...grpc.CallOption) (*Status, error)
	// Applicable on authenticated requests or on requests with active authentication process with
	// at least one factor passed
	ListMyIdentitiesAndVerifiers(ctx context.Context, in *ListMyIdentitiesAndVerifiersReq, opts ...grpc.CallOption) (*ListMyIdentitiesAndVerifiersResp, error)
	Start(ctx context.Context, in *StartReq, opts ...grpc.CallOption) (*StartResp, error)
	Verify(ctx context.Context, in *VerifyReq, opts ...grpc.CallOption) (*Status, error)
}

type identityClient struct {
	cc *grpc.ClientConn
}

func NewIdentityClient(cc *grpc.ClientConn) IdentityClient {
	return &identityClient{cc}
}

func (c *identityClient) ListSupportedIdentitiesAndVerifiers(ctx context.Context, in *ListSupportedIdentitiesAndVerifiersReq, opts ...grpc.CallOption) (*VerifierDetailsResp, error) {
	out := new(VerifierDetailsResp)
	err := c.cc.Invoke(ctx, "/api.themakers.identity.Identity/ListSupportedIdentitiesAndVerifiers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityClient) CheckStatus(ctx context.Context, in *StatusReq, opts ...grpc.CallOption) (*Status, error) {
	out := new(Status)
	err := c.cc.Invoke(ctx, "/api.themakers.identity.Identity/CheckStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityClient) Logout(ctx context.Context, in *LogoutReq, opts ...grpc.CallOption) (*Status, error) {
	out := new(Status)
	err := c.cc.Invoke(ctx, "/api.themakers.identity.Identity/Logout", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityClient) UserMerge(ctx context.Context, in *UserMergeReq, opts ...grpc.CallOption) (*UserMergeResp, error) {
	out := new(UserMergeResp)
	err := c.cc.Invoke(ctx, "/api.themakers.identity.Identity/UserMerge", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityClient) StartSignIn(ctx context.Context, in *StartSignInReq, opts ...grpc.CallOption) (*Status, error) {
	out := new(Status)
	err := c.cc.Invoke(ctx, "/api.themakers.identity.Identity/StartSignIn", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityClient) StartSignUp(ctx context.Context, in *StartSignUpReq, opts ...grpc.CallOption) (*Status, error) {
	out := new(Status)
	err := c.cc.Invoke(ctx, "/api.themakers.identity.Identity/StartSignUp", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityClient) StartAttach(ctx context.Context, in *StartAttachReq, opts ...grpc.CallOption) (*Status, error) {
	out := new(Status)
	err := c.cc.Invoke(ctx, "/api.themakers.identity.Identity/StartAttach", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityClient) CancelAuthentication(ctx context.Context, in *CancelAuthenticationReq, opts ...grpc.CallOption) (*Status, error) {
	out := new(Status)
	err := c.cc.Invoke(ctx, "/api.themakers.identity.Identity/CancelAuthentication", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityClient) ListMyIdentitiesAndVerifiers(ctx context.Context, in *ListMyIdentitiesAndVerifiersReq, opts ...grpc.CallOption) (*ListMyIdentitiesAndVerifiersResp, error) {
	out := new(ListMyIdentitiesAndVerifiersResp)
	err := c.cc.Invoke(ctx, "/api.themakers.identity.Identity/ListMyIdentitiesAndVerifiers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityClient) Start(ctx context.Context, in *StartReq, opts ...grpc.CallOption) (*StartResp, error) {
	out := new(StartResp)
	err := c.cc.Invoke(ctx, "/api.themakers.identity.Identity/Start", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityClient) Verify(ctx context.Context, in *VerifyReq, opts ...grpc.CallOption) (*Status, error) {
	out := new(Status)
	err := c.cc.Invoke(ctx, "/api.themakers.identity.Identity/Verify", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IdentityServer is the server API for Identity service.
type IdentityServer interface {
	ListSupportedIdentitiesAndVerifiers(context.Context, *ListSupportedIdentitiesAndVerifiersReq) (*VerifierDetailsResp, error)
	CheckStatus(context.Context, *StatusReq) (*Status, error)
	Logout(context.Context, *LogoutReq) (*Status, error)
	UserMerge(context.Context, *UserMergeReq) (*UserMergeResp, error)
	// > Only applicable to unauthenticated requests
	//  Will NOT create/modify any new user record
	//  As result of successful authentication
	//    existing user will be signed in
	StartSignIn(context.Context, *StartSignInReq) (*Status, error)
	// > Only applicable to unauthenticated requests
	//  WILL create new user record; Can only use new (unregistered) identities
	//  As result of successful authentication
	//    new user will be created
	//    or existing user will be signed in
	StartSignUp(context.Context, *StartSignUpReq) (*Status, error)
	// > Only applicable to authenticated requests
	//  Will add new verifier/identity to existing user
	//  As result of successful authentication
	//    new identity/verifier will be added to existing user
	StartAttach(context.Context, *StartAttachReq) (*Status, error)
	// //////////////////////////////////////////////////////////////
	// // Working within authentication process
	//
	// This methods can be called only when there is an active authentication process
	//
	CancelAuthentication(context.Context, *CancelAuthenticationReq) (*Status, error)
	// Applicable on authenticated requests or on requests with active authentication process with
	// at least one factor passed
	ListMyIdentitiesAndVerifiers(context.Context, *ListMyIdentitiesAndVerifiersReq) (*ListMyIdentitiesAndVerifiersResp, error)
	Start(context.Context, *StartReq) (*StartResp, error)
	Verify(context.Context, *VerifyReq) (*Status, error)
}

func RegisterIdentityServer(s *grpc.Server, srv IdentityServer) {
	s.RegisterService(&_Identity_serviceDesc, srv)
}

func _Identity_ListSupportedIdentitiesAndVerifiers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSupportedIdentitiesAndVerifiersReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServer).ListSupportedIdentitiesAndVerifiers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.themakers.identity.Identity/ListSupportedIdentitiesAndVerifiers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServer).ListSupportedIdentitiesAndVerifiers(ctx, req.(*ListSupportedIdentitiesAndVerifiersReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Identity_CheckStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServer).CheckStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.themakers.identity.Identity/CheckStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServer).CheckStatus(ctx, req.(*StatusReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Identity_Logout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogoutReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServer).Logout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.themakers.identity.Identity/Logout",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServer).Logout(ctx, req.(*LogoutReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Identity_UserMerge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserMergeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServer).UserMerge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.themakers.identity.Identity/UserMerge",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServer).UserMerge(ctx, req.(*UserMergeReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Identity_StartSignIn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartSignInReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServer).StartSignIn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.themakers.identity.Identity/StartSignIn",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServer).StartSignIn(ctx, req.(*StartSignInReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Identity_StartSignUp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartSignUpReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServer).StartSignUp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.themakers.identity.Identity/StartSignUp",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServer).StartSignUp(ctx, req.(*StartSignUpReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Identity_StartAttach_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartAttachReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServer).StartAttach(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.themakers.identity.Identity/StartAttach",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServer).StartAttach(ctx, req.(*StartAttachReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Identity_CancelAuthentication_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelAuthenticationReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServer).CancelAuthentication(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.themakers.identity.Identity/CancelAuthentication",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServer).CancelAuthentication(ctx, req.(*CancelAuthenticationReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Identity_ListMyIdentitiesAndVerifiers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMyIdentitiesAndVerifiersReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServer).ListMyIdentitiesAndVerifiers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.themakers.identity.Identity/ListMyIdentitiesAndVerifiers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServer).ListMyIdentitiesAndVerifiers(ctx, req.(*ListMyIdentitiesAndVerifiersReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Identity_Start_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServer).Start(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.themakers.identity.Identity/Start",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServer).Start(ctx, req.(*StartReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Identity_Verify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServer).Verify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.themakers.identity.Identity/Verify",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServer).Verify(ctx, req.(*VerifyReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Identity_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.themakers.identity.Identity",
	HandlerType: (*IdentityServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListSupportedIdentitiesAndVerifiers",
			Handler:    _Identity_ListSupportedIdentitiesAndVerifiers_Handler,
		},
		{
			MethodName: "CheckStatus",
			Handler:    _Identity_CheckStatus_Handler,
		},
		{
			MethodName: "Logout",
			Handler:    _Identity_Logout_Handler,
		},
		{
			MethodName: "UserMerge",
			Handler:    _Identity_UserMerge_Handler,
		},
		{
			MethodName: "StartSignIn",
			Handler:    _Identity_StartSignIn_Handler,
		},
		{
			MethodName: "StartSignUp",
			Handler:    _Identity_StartSignUp_Handler,
		},
		{
			MethodName: "StartAttach",
			Handler:    _Identity_StartAttach_Handler,
		},
		{
			MethodName: "CancelAuthentication",
			Handler:    _Identity_CancelAuthentication_Handler,
		},
		{
			MethodName: "ListMyIdentitiesAndVerifiers",
			Handler:    _Identity_ListMyIdentitiesAndVerifiers_Handler,
		},
		{
			MethodName: "Start",
			Handler:    _Identity_Start_Handler,
		},
		{
			MethodName: "Verify",
			Handler:    _Identity_Verify_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "identity.proto",
}

// IdentityPrivateClient is the client API for IdentityPrivate service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type IdentityPrivateClient interface {
	LoginAs(ctx context.Context, in *LoginAsReq, opts ...grpc.CallOption) (*LoginAsResp, error)
}

type identityPrivateClient struct {
	cc *grpc.ClientConn
}

func NewIdentityPrivateClient(cc *grpc.ClientConn) IdentityPrivateClient {
	return &identityPrivateClient{cc}
}

func (c *identityPrivateClient) LoginAs(ctx context.Context, in *LoginAsReq, opts ...grpc.CallOption) (*LoginAsResp, error) {
	out := new(LoginAsResp)
	err := c.cc.Invoke(ctx, "/api.themakers.identity.IdentityPrivate/LoginAs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IdentityPrivateServer is the server API for IdentityPrivate service.
type IdentityPrivateServer interface {
	LoginAs(context.Context, *LoginAsReq) (*LoginAsResp, error)
}

func RegisterIdentityPrivateServer(s *grpc.Server, srv IdentityPrivateServer) {
	s.RegisterService(&_IdentityPrivate_serviceDesc, srv)
}

func _IdentityPrivate_LoginAs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginAsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityPrivateServer).LoginAs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.themakers.identity.IdentityPrivate/LoginAs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityPrivateServer).LoginAs(ctx, req.(*LoginAsReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _IdentityPrivate_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.themakers.identity.IdentityPrivate",
	HandlerType: (*IdentityPrivateServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "LoginAs",
			Handler:    _IdentityPrivate_LoginAs_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "identity.proto",
}

func init() { proto.RegisterFile("identity.proto", fileDescriptor_identity_30fb4ee92ce8cf34) }

var fileDescriptor_identity_30fb4ee92ce8cf34 = []byte{
	// 1072 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x57, 0x5f, 0x6f, 0x1b, 0x45,
	0x10, 0xe7, 0x62, 0xd7, 0xb5, 0xe7, 0x1a, 0xc7, 0xda, 0x46, 0xe5, 0x30, 0x11, 0x38, 0xd7, 0x12,
	0x4c, 0x0a, 0x46, 0x98, 0x87, 0x16, 0xa4, 0x46, 0xb8, 0x49, 0x10, 0x11, 0x29, 0x6d, 0xce, 0x35,
	0xaa, 0xfa, 0x82, 0xae, 0xf6, 0xe2, 0x2c, 0x71, 0xee, 0xb6, 0xb7, 0xeb, 0x48, 0x46, 0x3c, 0x22,
	0xde, 0xe1, 0x15, 0xf1, 0x29, 0x10, 0x9f, 0x81, 0x27, 0x3e, 0x06, 0xe2, 0x33, 0xf0, 0x86, 0xf6,
	0xcf, 0x9d, 0xef, 0x2e, 0xbe, 0x3f, 0x41, 0x88, 0x27, 0x7b, 0x66, 0x67, 0x7e, 0x3b, 0x3b, 0x33,
	0xfb, 0xdb, 0x39, 0x68, 0x92, 0x09, 0xf6, 0x38, 0xe1, 0x8b, 0x1e, 0x0d, 0x7c, 0xee, 0xa3, 0x5b,
	0x2e, 0x25, 0x3d, 0x7e, 0x8a, 0xcf, 0xdd, 0x33, 0x1c, 0xb0, 0x5e, 0xb8, 0x6a, 0xb7, 0xa0, 0x39,
	0xe4, 0x6e, 0xc0, 0x87, 0x64, 0xea, 0x1d, 0x79, 0x0e, 0x7e, 0x99, 0xd0, 0x8c, 0x68, 0x5c, 0x33,
	0xe0, 0xdc, 0x1d, 0x9f, 0x0a, 0x4d, 0x17, 0x76, 0x8e, 0x09, 0xe3, 0xc3, 0x39, 0xa5, 0x7e, 0xc0,
	0xf1, 0xe4, 0x48, 0xc1, 0x11, 0xcc, 0x06, 0xde, 0xe4, 0x4b, 0x1c, 0x90, 0xaf, 0x09, 0x0e, 0x98,
	0xb0, 0xdc, 0x86, 0x37, 0x85, 0xe5, 0xa3, 0x45, 0xb6, 0xc9, 0xf7, 0x06, 0xdc, 0x0c, 0x15, 0x07,
	0x98, 0xbb, 0x64, 0xc6, 0x1c, 0xcc, 0x28, 0xda, 0x81, 0x66, 0xe8, 0xb4, 0xf8, 0xc2, 0x3d, 0xc7,
	0xcc, 0x32, 0x3a, 0x95, 0x6e, 0xc3, 0x49, 0x69, 0xd1, 0x21, 0x34, 0x22, 0x3c, 0x6b, 0xad, 0x53,
	0xe9, 0x9a, 0xfd, 0xb7, 0x7b, 0xab, 0x8f, 0xdb, 0x4b, 0xef, 0xb3, 0xf4, 0xb4, 0xff, 0x34, 0x60,
	0x23, 0xb5, 0x8c, 0x10, 0x54, 0xc5, 0x1e, 0x96, 0xd1, 0x31, 0xba, 0x0d, 0x47, 0xfe, 0x47, 0x36,
	0xdc, 0xd0, 0x01, 0xc8, 0xfd, 0xad, 0x35, 0xb9, 0x96, 0xd0, 0x89, 0xd0, 0x75, 0x6e, 0x1c, 0x3c,
	0x9d, 0xcf, 0xdc, 0xc0, 0xaa, 0x74, 0x8c, 0x6e, 0xdd, 0x49, 0x69, 0x13, 0x76, 0x17, 0x38, 0x60,
	0xd8, 0xaa, 0xa6, 0xec, 0xa4, 0x16, 0xdd, 0x81, 0x75, 0xad, 0x79, 0x3c, 0x98, 0xf3, 0xd3, 0xbe,
	0x75, 0x4d, 0x9a, 0x25, 0x95, 0x31, 0xab, 0x21, 0x77, 0x39, 0x19, 0x5b, 0xb5, 0x84, 0x95, 0x52,
	0xda, 0x3f, 0x18, 0xd0, 0xc9, 0x2f, 0x09, 0xa3, 0xe8, 0x00, 0x60, 0xb9, 0x2a, 0xf3, 0x6e, 0xf6,
	0xef, 0x64, 0x25, 0x35, 0x3c, 0xfa, 0x81, 0xcb, 0x5d, 0x27, 0xe6, 0x87, 0xb6, 0xd2, 0x95, 0x69,
	0xc4, 0x13, 0xbe, 0xb7, 0x4c, 0xa4, 0xf0, 0x5c, 0x99, 0xec, 0x36, 0xd4, 0x43, 0x1b, 0x9d, 0xe8,
	0x48, 0xb6, 0xff, 0x32, 0xa0, 0x2e, 0xfb, 0xd2, 0xc1, 0x2f, 0x45, 0x55, 0x42, 0xe4, 0x18, 0x48,
	0x42, 0x57, 0xaa, 0x72, 0xf1, 0x0d, 0x2b, 0xc9, 0x0d, 0xd1, 0x1e, 0x54, 0x07, 0xc1, 0x94, 0x59,
	0x55, 0x99, 0x8e, 0xdd, 0xac, 0x74, 0x84, 0x31, 0xf5, 0x84, 0xf1, 0xa1, 0xc7, 0x83, 0x85, 0x23,
	0xfd, 0xda, 0xf7, 0xa0, 0x11, 0xa9, 0x50, 0x0b, 0x2a, 0x67, 0x78, 0xa1, 0xe3, 0x14, 0x7f, 0xd1,
	0x26, 0x5c, 0xbb, 0x70, 0x67, 0xf3, 0x30, 0x2e, 0x25, 0x7c, 0xbc, 0x76, 0xdf, 0xb0, 0x7f, 0x31,
	0xa0, 0xa1, 0x51, 0x19, 0x45, 0x27, 0x00, 0x07, 0x24, 0xc0, 0x63, 0x4e, 0x7c, 0x8f, 0x59, 0x15,
	0x19, 0xcc, 0x07, 0x05, 0xc1, 0x30, 0xda, 0x5b, 0xfa, 0xa8, 0x98, 0x62, 0x20, 0xed, 0x07, 0xb0,
	0x91, 0x5a, 0xbe, 0x52, 0x7c, 0xa6, 0x0c, 0x8f, 0xcf, 0xe5, 0x75, 0xfe, 0xdd, 0x80, 0x9a, 0x92,
	0x84, 0xc7, 0x53, 0xff, 0x0c, 0x7b, 0x1a, 0x45, 0x09, 0xe8, 0x29, 0x34, 0x45, 0xbf, 0x8a, 0x00,
	0xc7, 0x2e, 0x27, 0xde, 0x54, 0x02, 0x9a, 0xfd, 0x77, 0x73, 0xce, 0xc0, 0xe7, 0x2c, 0xe9, 0xe3,
	0xa4, 0x30, 0xd0, 0x09, 0xac, 0xc7, 0x34, 0x78, 0x22, 0xab, 0x67, 0xf6, 0xef, 0x96, 0x06, 0xc5,
	0x13, 0x27, 0x89, 0x60, 0xbf, 0x03, 0x37, 0x57, 0x58, 0x89, 0x3e, 0x1d, 0x31, 0x1c, 0x84, 0x7d,
	0x2a, 0xfe, 0xdb, 0x7f, 0x1b, 0xb0, 0xb9, 0x2a, 0x4c, 0x64, 0x41, 0x4d, 0x51, 0xab, 0x34, 0xaf,
	0x7f, 0xf6, 0x8a, 0xa3, 0xe5, 0x70, 0x65, 0x44, 0xe5, 0xf1, 0xa3, 0x95, 0x11, 0x15, 0x2b, 0x8a,
	0x6a, 0x15, 0x6b, 0x88, 0x15, 0x25, 0xa3, 0xe7, 0xd0, 0xda, 0xf7, 0xcf, 0xe9, 0x0c, 0x73, 0x3c,
	0xf9, 0xd4, 0x1d, 0x73, 0x3f, 0x08, 0xbb, 0xb1, 0x97, 0x7f, 0xce, 0xb4, 0x97, 0x73, 0x09, 0x07,
	0xed, 0x42, 0xcb, 0xc1, 0xe7, 0x2e, 0xf1, 0x88, 0x37, 0x0d, 0xb1, 0x05, 0xcd, 0x54, 0x9c, 0x4b,
	0xfa, 0x87, 0x26, 0x34, 0x1e, 0xbf, 0xf8, 0x46, 0xf4, 0xcb, 0x05, 0xb6, 0xbf, 0x83, 0x5b, 0xab,
	0x37, 0xf9, 0x3f, 0x2e, 0xa5, 0xdd, 0x84, 0x1b, 0xa2, 0x02, 0x8f, 0x70, 0x30, 0xc5, 0xa2, 0xfd,
	0x36, 0x60, 0x3d, 0x26, 0x33, 0x6a, 0xbf, 0x06, 0xaf, 0xee, 0xbb, 0xde, 0x18, 0xcf, 0xe2, 0x95,
	0xf1, 0xe5, 0x53, 0xf7, 0x1e, 0x34, 0x8e, 0xfd, 0xa9, 0x3f, 0x97, 0x0c, 0xd2, 0x01, 0x73, 0x30,
	0x9b, 0x0d, 0x31, 0x63, 0xf2, 0x5e, 0xc9, 0x72, 0x39, 0x71, 0x95, 0xfd, 0x87, 0x01, 0xaf, 0x1f,
	0x79, 0x84, 0x13, 0x77, 0x46, 0xbe, 0xc5, 0x8a, 0x4e, 0xc3, 0xb3, 0x94, 0xe5, 0xa0, 0x13, 0xcd,
	0x21, 0xea, 0x9d, 0x7a, 0x90, 0x49, 0xa9, 0xd9, 0xdb, 0xfc, 0x77, 0xb4, 0xf2, 0xab, 0x01, 0x5b,
	0xd9, 0x1b, 0x31, 0x8a, 0x9e, 0x41, 0xcd, 0xc1, 0x6c, 0x3e, 0xe3, 0xfa, 0x05, 0xf8, 0xe4, 0xea,
	0xe1, 0x32, 0xda, 0x53, 0x10, 0x2a, 0x62, 0x8d, 0xd7, 0xfe, 0x08, 0xcc, 0x98, 0xfa, 0x4a, 0x51,
	0xff, 0x6c, 0xe8, 0x57, 0x65, 0x51, 0x36, 0xe7, 0xbb, 0xd0, 0x52, 0xb2, 0xaa, 0xfc, 0xbe, 0x3f,
	0x09, 0x61, 0x2f, 0xe9, 0x2f, 0xb5, 0x63, 0xa5, 0xa0, 0x1d, 0xab, 0xa9, 0x76, 0xec, 0x00, 0x1c,
	0xfb, 0x53, 0xe2, 0x0d, 0x04, 0x17, 0xae, 0xa4, 0x8a, 0x13, 0x30, 0x23, 0x0b, 0x26, 0x2e, 0xfb,
	0x75, 0xdd, 0x60, 0xda, 0x2a, 0x14, 0x23, 0xe7, 0xb5, 0xa5, 0xb3, 0x48, 0xcb, 0x61, 0x10, 0xf8,
	0x81, 0x8e, 0x4b, 0x09, 0xfd, 0xdf, 0xea, 0xcb, 0x88, 0xd0, 0x4f, 0x06, 0xdc, 0x2e, 0x31, 0x9c,
	0xa1, 0xbd, 0xac, 0x62, 0x96, 0x9b, 0xec, 0xda, 0x77, 0xcb, 0xce, 0x58, 0xe2, 0x94, 0x4f, 0xc0,
	0xdc, 0x3f, 0xc5, 0xe3, 0x33, 0xfd, 0x30, 0x6c, 0xe7, 0xb3, 0x95, 0x80, 0x7f, 0x23, 0xdf, 0x04,
	0x7d, 0x0e, 0x35, 0x75, 0x77, 0xb3, 0xc1, 0xa2, 0xbb, 0x5d, 0x08, 0xf6, 0x0c, 0x1a, 0x11, 0x69,
	0xa0, 0xcc, 0x39, 0x27, 0xce, 0x33, 0xed, 0xb7, 0x4a, 0x58, 0x31, 0x8a, 0x46, 0x60, 0xc6, 0xe6,
	0x6b, 0xb4, 0x93, 0xfb, 0x4e, 0x47, 0x43, 0x78, 0x61, 0xc0, 0x71, 0xd8, 0x11, 0x2d, 0x01, 0x2b,
	0x27, 0xf9, 0xd2, 0xb0, 0xfa, 0xb9, 0xc9, 0x87, 0x8d, 0x3e, 0x07, 0x0a, 0x61, 0xa7, 0xb0, 0xb9,
	0x8a, 0x82, 0xd1, 0xfb, 0x59, 0x7e, 0x19, 0x84, 0x5d, 0xb8, 0xd1, 0x8f, 0x06, 0x6c, 0xe5, 0xcd,
	0xb6, 0xe8, 0x5e, 0x5e, 0xd3, 0xe7, 0x7c, 0xa4, 0xb4, 0xef, 0xff, 0x3b, 0x47, 0x46, 0xd1, 0x31,
	0x5c, 0x93, 0xe9, 0x42, 0x9d, 0xa2, 0x81, 0xb1, 0xbd, 0x5d, 0x38, 0xc5, 0x89, 0xb6, 0x57, 0xe4,
	0x97, 0xdd, 0xf6, 0x11, 0x39, 0x16, 0xa5, 0xab, 0x8f, 0x61, 0x23, 0xa4, 0x8d, 0x27, 0x01, 0xb9,
	0x70, 0x39, 0x46, 0x0e, 0x5c, 0xd7, 0xec, 0x84, 0xec, 0x9c, 0x7b, 0xa5, 0x09, 0xae, 0x7d, 0xbb,
	0xd0, 0x86, 0xd1, 0x87, 0xad, 0xe7, 0xd1, 0xd7, 0xe8, 0x57, 0xf2, 0x6b, 0xf4, 0x45, 0x4d, 0xfe,
	0x7c, 0xf8, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x6b, 0x35, 0x14, 0x15, 0xa6, 0x0e, 0x00, 0x00,
}
