// Code generated by protoc-gen-go. DO NOT EDIT.
// source: identity.proto

package identity_proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Dummy struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Dummy) Reset()         { *m = Dummy{} }
func (m *Dummy) String() string { return proto.CompactTextString(m) }
func (*Dummy) ProtoMessage()    {}
func (*Dummy) Descriptor() ([]byte, []int) {
	return fileDescriptor_61c7956abb761639, []int{0}
}

func (m *Dummy) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Dummy.Unmarshal(m, b)
}
func (m *Dummy) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Dummy.Marshal(b, m, deterministic)
}
func (m *Dummy) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Dummy.Merge(m, src)
}
func (m *Dummy) XXX_Size() int {
	return xxx_messageInfo_Dummy.Size(m)
}
func (m *Dummy) XXX_DiscardUnknown() {
	xxx_messageInfo_Dummy.DiscardUnknown(m)
}

var xxx_messageInfo_Dummy proto.InternalMessageInfo

//// ListMessages
type VerifiersDetailsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VerifiersDetailsRequest) Reset()         { *m = VerifiersDetailsRequest{} }
func (m *VerifiersDetailsRequest) String() string { return proto.CompactTextString(m) }
func (*VerifiersDetailsRequest) ProtoMessage()    {}
func (*VerifiersDetailsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_61c7956abb761639, []int{1}
}

func (m *VerifiersDetailsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifiersDetailsRequest.Unmarshal(m, b)
}
func (m *VerifiersDetailsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifiersDetailsRequest.Marshal(b, m, deterministic)
}
func (m *VerifiersDetailsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifiersDetailsRequest.Merge(m, src)
}
func (m *VerifiersDetailsRequest) XXX_Size() int {
	return xxx_messageInfo_VerifiersDetailsRequest.Size(m)
}
func (m *VerifiersDetailsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifiersDetailsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_VerifiersDetailsRequest proto.InternalMessageInfo

type VerifierDetailsResponse struct {
	IdentitiyNames       []string           `protobuf:"bytes,1,rep,name=IdentitiyNames,proto3" json:"IdentitiyNames,omitempty"`
	Verifiers            []*VerifierDetails `protobuf:"bytes,2,rep,name=Verifiers,proto3" json:"Verifiers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *VerifierDetailsResponse) Reset()         { *m = VerifierDetailsResponse{} }
func (m *VerifierDetailsResponse) String() string { return proto.CompactTextString(m) }
func (*VerifierDetailsResponse) ProtoMessage()    {}
func (*VerifierDetailsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_61c7956abb761639, []int{2}
}

func (m *VerifierDetailsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifierDetailsResponse.Unmarshal(m, b)
}
func (m *VerifierDetailsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifierDetailsResponse.Marshal(b, m, deterministic)
}
func (m *VerifierDetailsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifierDetailsResponse.Merge(m, src)
}
func (m *VerifierDetailsResponse) XXX_Size() int {
	return xxx_messageInfo_VerifierDetailsResponse.Size(m)
}
func (m *VerifierDetailsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifierDetailsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_VerifierDetailsResponse proto.InternalMessageInfo

func (m *VerifierDetailsResponse) GetIdentitiyNames() []string {
	if m != nil {
		return m.IdentitiyNames
	}
	return nil
}

func (m *VerifierDetailsResponse) GetVerifiers() []*VerifierDetails {
	if m != nil {
		return m.Verifiers
	}
	return nil
}

type MyVerifiersDetailRequest struct {
	Identity             string   `protobuf:"bytes,1,opt,name=Identity,proto3" json:"Identity,omitempty"`
	VerifierName         string   `protobuf:"bytes,2,opt,name=VerifierName,proto3" json:"VerifierName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MyVerifiersDetailRequest) Reset()         { *m = MyVerifiersDetailRequest{} }
func (m *MyVerifiersDetailRequest) String() string { return proto.CompactTextString(m) }
func (*MyVerifiersDetailRequest) ProtoMessage()    {}
func (*MyVerifiersDetailRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_61c7956abb761639, []int{3}
}

func (m *MyVerifiersDetailRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MyVerifiersDetailRequest.Unmarshal(m, b)
}
func (m *MyVerifiersDetailRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MyVerifiersDetailRequest.Marshal(b, m, deterministic)
}
func (m *MyVerifiersDetailRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MyVerifiersDetailRequest.Merge(m, src)
}
func (m *MyVerifiersDetailRequest) XXX_Size() int {
	return xxx_messageInfo_MyVerifiersDetailRequest.Size(m)
}
func (m *MyVerifiersDetailRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MyVerifiersDetailRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MyVerifiersDetailRequest proto.InternalMessageInfo

func (m *MyVerifiersDetailRequest) GetIdentity() string {
	if m != nil {
		return m.Identity
	}
	return ""
}

func (m *MyVerifiersDetailRequest) GetVerifierName() string {
	if m != nil {
		return m.VerifierName
	}
	return ""
}

type StartVerificationReq struct {
	VerifierName         string            `protobuf:"bytes,1,opt,name=VerifierName,proto3" json:"VerifierName,omitempty"`
	Identity             string            `protobuf:"bytes,2,opt,name=Identity,proto3" json:"Identity,omitempty"`
	VerificationData     map[string][]byte `protobuf:"bytes,3,rep,name=VerificationData,proto3" json:"VerificationData,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *StartVerificationReq) Reset()         { *m = StartVerificationReq{} }
func (m *StartVerificationReq) String() string { return proto.CompactTextString(m) }
func (*StartVerificationReq) ProtoMessage()    {}
func (*StartVerificationReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_61c7956abb761639, []int{4}
}

func (m *StartVerificationReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartVerificationReq.Unmarshal(m, b)
}
func (m *StartVerificationReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartVerificationReq.Marshal(b, m, deterministic)
}
func (m *StartVerificationReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartVerificationReq.Merge(m, src)
}
func (m *StartVerificationReq) XXX_Size() int {
	return xxx_messageInfo_StartVerificationReq.Size(m)
}
func (m *StartVerificationReq) XXX_DiscardUnknown() {
	xxx_messageInfo_StartVerificationReq.DiscardUnknown(m)
}

var xxx_messageInfo_StartVerificationReq proto.InternalMessageInfo

func (m *StartVerificationReq) GetVerifierName() string {
	if m != nil {
		return m.VerifierName
	}
	return ""
}

func (m *StartVerificationReq) GetIdentity() string {
	if m != nil {
		return m.Identity
	}
	return ""
}

func (m *StartVerificationReq) GetVerificationData() map[string][]byte {
	if m != nil {
		return m.VerificationData
	}
	return nil
}

type StartVerificationResp struct {
	VerifierName         string   `protobuf:"bytes,1,opt,name=VerifierName,proto3" json:"VerifierName,omitempty"`
	VerificationCode     string   `protobuf:"bytes,2,opt,name=VerificationCode,proto3" json:"VerificationCode,omitempty"`
	Identity             string   `protobuf:"bytes,3,opt,name=Identity,proto3" json:"Identity,omitempty"`
	IdentityName         string   `protobuf:"bytes,4,opt,name=IdentityName,proto3" json:"IdentityName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StartVerificationResp) Reset()         { *m = StartVerificationResp{} }
func (m *StartVerificationResp) String() string { return proto.CompactTextString(m) }
func (*StartVerificationResp) ProtoMessage()    {}
func (*StartVerificationResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_61c7956abb761639, []int{5}
}

func (m *StartVerificationResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartVerificationResp.Unmarshal(m, b)
}
func (m *StartVerificationResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartVerificationResp.Marshal(b, m, deterministic)
}
func (m *StartVerificationResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartVerificationResp.Merge(m, src)
}
func (m *StartVerificationResp) XXX_Size() int {
	return xxx_messageInfo_StartVerificationResp.Size(m)
}
func (m *StartVerificationResp) XXX_DiscardUnknown() {
	xxx_messageInfo_StartVerificationResp.DiscardUnknown(m)
}

var xxx_messageInfo_StartVerificationResp proto.InternalMessageInfo

func (m *StartVerificationResp) GetVerifierName() string {
	if m != nil {
		return m.VerifierName
	}
	return ""
}

func (m *StartVerificationResp) GetVerificationCode() string {
	if m != nil {
		return m.VerificationCode
	}
	return ""
}

func (m *StartVerificationResp) GetIdentity() string {
	if m != nil {
		return m.Identity
	}
	return ""
}

func (m *StartVerificationResp) GetIdentityName() string {
	if m != nil {
		return m.IdentityName
	}
	return ""
}

type StatusReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StatusReq) Reset()         { *m = StatusReq{} }
func (m *StatusReq) String() string { return proto.CompactTextString(m) }
func (*StatusReq) ProtoMessage()    {}
func (*StatusReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_61c7956abb761639, []int{6}
}

func (m *StatusReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatusReq.Unmarshal(m, b)
}
func (m *StatusReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatusReq.Marshal(b, m, deterministic)
}
func (m *StatusReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatusReq.Merge(m, src)
}
func (m *StatusReq) XXX_Size() int {
	return xxx_messageInfo_StatusReq.Size(m)
}
func (m *StatusReq) XXX_DiscardUnknown() {
	xxx_messageInfo_StatusReq.DiscardUnknown(m)
}

var xxx_messageInfo_StatusReq proto.InternalMessageInfo

type Status struct {
	Authenticated        bool     `protobuf:"varint,1,opt,name=Authenticated,proto3" json:"Authenticated,omitempty"`
	Authenticating       bool     `protobuf:"varint,2,opt,name=Authenticating,proto3" json:"Authenticating,omitempty"`
	RemainingFactors     int64    `protobuf:"varint,3,opt,name=RemainingFactors,proto3" json:"RemainingFactors,omitempty"`
	SessionID            string   `protobuf:"bytes,4,opt,name=SessionID,proto3" json:"SessionID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Status) Reset()         { *m = Status{} }
func (m *Status) String() string { return proto.CompactTextString(m) }
func (*Status) ProtoMessage()    {}
func (*Status) Descriptor() ([]byte, []int) {
	return fileDescriptor_61c7956abb761639, []int{7}
}

func (m *Status) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Status.Unmarshal(m, b)
}
func (m *Status) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Status.Marshal(b, m, deterministic)
}
func (m *Status) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Status.Merge(m, src)
}
func (m *Status) XXX_Size() int {
	return xxx_messageInfo_Status.Size(m)
}
func (m *Status) XXX_DiscardUnknown() {
	xxx_messageInfo_Status.DiscardUnknown(m)
}

var xxx_messageInfo_Status proto.InternalMessageInfo

func (m *Status) GetAuthenticated() bool {
	if m != nil {
		return m.Authenticated
	}
	return false
}

func (m *Status) GetAuthenticating() bool {
	if m != nil {
		return m.Authenticating
	}
	return false
}

func (m *Status) GetRemainingFactors() int64 {
	if m != nil {
		return m.RemainingFactors
	}
	return 0
}

func (m *Status) GetSessionID() string {
	if m != nil {
		return m.SessionID
	}
	return ""
}

type UserMergeReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserMergeReq) Reset()         { *m = UserMergeReq{} }
func (m *UserMergeReq) String() string { return proto.CompactTextString(m) }
func (*UserMergeReq) ProtoMessage()    {}
func (*UserMergeReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_61c7956abb761639, []int{8}
}

func (m *UserMergeReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserMergeReq.Unmarshal(m, b)
}
func (m *UserMergeReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserMergeReq.Marshal(b, m, deterministic)
}
func (m *UserMergeReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserMergeReq.Merge(m, src)
}
func (m *UserMergeReq) XXX_Size() int {
	return xxx_messageInfo_UserMergeReq.Size(m)
}
func (m *UserMergeReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UserMergeReq.DiscardUnknown(m)
}

var xxx_messageInfo_UserMergeReq proto.InternalMessageInfo

type UserMergeResp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserMergeResp) Reset()         { *m = UserMergeResp{} }
func (m *UserMergeResp) String() string { return proto.CompactTextString(m) }
func (*UserMergeResp) ProtoMessage()    {}
func (*UserMergeResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_61c7956abb761639, []int{9}
}

func (m *UserMergeResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserMergeResp.Unmarshal(m, b)
}
func (m *UserMergeResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserMergeResp.Marshal(b, m, deterministic)
}
func (m *UserMergeResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserMergeResp.Merge(m, src)
}
func (m *UserMergeResp) XXX_Size() int {
	return xxx_messageInfo_UserMergeResp.Size(m)
}
func (m *UserMergeResp) XXX_DiscardUnknown() {
	xxx_messageInfo_UserMergeResp.DiscardUnknown(m)
}

var xxx_messageInfo_UserMergeResp proto.InternalMessageInfo

type CancelAuthenticationReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CancelAuthenticationReq) Reset()         { *m = CancelAuthenticationReq{} }
func (m *CancelAuthenticationReq) String() string { return proto.CompactTextString(m) }
func (*CancelAuthenticationReq) ProtoMessage()    {}
func (*CancelAuthenticationReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_61c7956abb761639, []int{10}
}

func (m *CancelAuthenticationReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CancelAuthenticationReq.Unmarshal(m, b)
}
func (m *CancelAuthenticationReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CancelAuthenticationReq.Marshal(b, m, deterministic)
}
func (m *CancelAuthenticationReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CancelAuthenticationReq.Merge(m, src)
}
func (m *CancelAuthenticationReq) XXX_Size() int {
	return xxx_messageInfo_CancelAuthenticationReq.Size(m)
}
func (m *CancelAuthenticationReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CancelAuthenticationReq.DiscardUnknown(m)
}

var xxx_messageInfo_CancelAuthenticationReq proto.InternalMessageInfo

type LogoutReq struct {
	AllSessions          bool     `protobuf:"varint,1,opt,name=AllSessions,proto3" json:"AllSessions,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogoutReq) Reset()         { *m = LogoutReq{} }
func (m *LogoutReq) String() string { return proto.CompactTextString(m) }
func (*LogoutReq) ProtoMessage()    {}
func (*LogoutReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_61c7956abb761639, []int{11}
}

func (m *LogoutReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogoutReq.Unmarshal(m, b)
}
func (m *LogoutReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogoutReq.Marshal(b, m, deterministic)
}
func (m *LogoutReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogoutReq.Merge(m, src)
}
func (m *LogoutReq) XXX_Size() int {
	return xxx_messageInfo_LogoutReq.Size(m)
}
func (m *LogoutReq) XXX_DiscardUnknown() {
	xxx_messageInfo_LogoutReq.DiscardUnknown(m)
}

var xxx_messageInfo_LogoutReq proto.InternalMessageInfo

func (m *LogoutReq) GetAllSessions() bool {
	if m != nil {
		return m.AllSessions
	}
	return false
}

type InitializeStaticVerifierReq struct {
	VerifierName         string            `protobuf:"bytes,1,opt,name=VerifierName,proto3" json:"VerifierName,omitempty"`
	InitalizationData    map[string][]byte `protobuf:"bytes,2,rep,name=InitalizationData,proto3" json:"InitalizationData,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *InitializeStaticVerifierReq) Reset()         { *m = InitializeStaticVerifierReq{} }
func (m *InitializeStaticVerifierReq) String() string { return proto.CompactTextString(m) }
func (*InitializeStaticVerifierReq) ProtoMessage()    {}
func (*InitializeStaticVerifierReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_61c7956abb761639, []int{12}
}

func (m *InitializeStaticVerifierReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InitializeStaticVerifierReq.Unmarshal(m, b)
}
func (m *InitializeStaticVerifierReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InitializeStaticVerifierReq.Marshal(b, m, deterministic)
}
func (m *InitializeStaticVerifierReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InitializeStaticVerifierReq.Merge(m, src)
}
func (m *InitializeStaticVerifierReq) XXX_Size() int {
	return xxx_messageInfo_InitializeStaticVerifierReq.Size(m)
}
func (m *InitializeStaticVerifierReq) XXX_DiscardUnknown() {
	xxx_messageInfo_InitializeStaticVerifierReq.DiscardUnknown(m)
}

var xxx_messageInfo_InitializeStaticVerifierReq proto.InternalMessageInfo

func (m *InitializeStaticVerifierReq) GetVerifierName() string {
	if m != nil {
		return m.VerifierName
	}
	return ""
}

func (m *InitializeStaticVerifierReq) GetInitalizationData() map[string][]byte {
	if m != nil {
		return m.InitalizationData
	}
	return nil
}

type InitializeStaticVerifierResp struct {
	InitializationResult []byte   `protobuf:"bytes,1,opt,name=InitializationResult,proto3" json:"InitializationResult,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InitializeStaticVerifierResp) Reset()         { *m = InitializeStaticVerifierResp{} }
func (m *InitializeStaticVerifierResp) String() string { return proto.CompactTextString(m) }
func (*InitializeStaticVerifierResp) ProtoMessage()    {}
func (*InitializeStaticVerifierResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_61c7956abb761639, []int{13}
}

func (m *InitializeStaticVerifierResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InitializeStaticVerifierResp.Unmarshal(m, b)
}
func (m *InitializeStaticVerifierResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InitializeStaticVerifierResp.Marshal(b, m, deterministic)
}
func (m *InitializeStaticVerifierResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InitializeStaticVerifierResp.Merge(m, src)
}
func (m *InitializeStaticVerifierResp) XXX_Size() int {
	return xxx_messageInfo_InitializeStaticVerifierResp.Size(m)
}
func (m *InitializeStaticVerifierResp) XXX_DiscardUnknown() {
	xxx_messageInfo_InitializeStaticVerifierResp.DiscardUnknown(m)
}

var xxx_messageInfo_InitializeStaticVerifierResp proto.InternalMessageInfo

func (m *InitializeStaticVerifierResp) GetInitializationResult() []byte {
	if m != nil {
		return m.InitializationResult
	}
	return nil
}

//// Authentication messages
type StartAuthenticationReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StartAuthenticationReq) Reset()         { *m = StartAuthenticationReq{} }
func (m *StartAuthenticationReq) String() string { return proto.CompactTextString(m) }
func (*StartAuthenticationReq) ProtoMessage()    {}
func (*StartAuthenticationReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_61c7956abb761639, []int{14}
}

func (m *StartAuthenticationReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartAuthenticationReq.Unmarshal(m, b)
}
func (m *StartAuthenticationReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartAuthenticationReq.Marshal(b, m, deterministic)
}
func (m *StartAuthenticationReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartAuthenticationReq.Merge(m, src)
}
func (m *StartAuthenticationReq) XXX_Size() int {
	return xxx_messageInfo_StartAuthenticationReq.Size(m)
}
func (m *StartAuthenticationReq) XXX_DiscardUnknown() {
	xxx_messageInfo_StartAuthenticationReq.DiscardUnknown(m)
}

var xxx_messageInfo_StartAuthenticationReq proto.InternalMessageInfo

type VerifyReq struct {
	VerifierName         string   `protobuf:"bytes,1,opt,name=VerifierName,proto3" json:"VerifierName,omitempty"`
	VerificationCode     string   `protobuf:"bytes,2,opt,name=VerificationCode,proto3" json:"VerificationCode,omitempty"`
	Identity             string   `protobuf:"bytes,3,opt,name=Identity,proto3" json:"Identity,omitempty"`
	IdentityName         string   `protobuf:"bytes,4,opt,name=IdentityName,proto3" json:"IdentityName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VerifyReq) Reset()         { *m = VerifyReq{} }
func (m *VerifyReq) String() string { return proto.CompactTextString(m) }
func (*VerifyReq) ProtoMessage()    {}
func (*VerifyReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_61c7956abb761639, []int{15}
}

func (m *VerifyReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyReq.Unmarshal(m, b)
}
func (m *VerifyReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyReq.Marshal(b, m, deterministic)
}
func (m *VerifyReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyReq.Merge(m, src)
}
func (m *VerifyReq) XXX_Size() int {
	return xxx_messageInfo_VerifyReq.Size(m)
}
func (m *VerifyReq) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyReq.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyReq proto.InternalMessageInfo

func (m *VerifyReq) GetVerifierName() string {
	if m != nil {
		return m.VerifierName
	}
	return ""
}

func (m *VerifyReq) GetVerificationCode() string {
	if m != nil {
		return m.VerificationCode
	}
	return ""
}

func (m *VerifyReq) GetIdentity() string {
	if m != nil {
		return m.Identity
	}
	return ""
}

func (m *VerifyReq) GetIdentityName() string {
	if m != nil {
		return m.IdentityName
	}
	return ""
}

/// TODO create structure of responses
type StartAuthenticationResp struct {
	VerificationDirections map[string]string `protobuf:"bytes,1,rep,name=VerificationDirections,proto3" json:"VerificationDirections,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral   struct{}          `json:"-"`
	XXX_unrecognized       []byte            `json:"-"`
	XXX_sizecache          int32             `json:"-"`
}

func (m *StartAuthenticationResp) Reset()         { *m = StartAuthenticationResp{} }
func (m *StartAuthenticationResp) String() string { return proto.CompactTextString(m) }
func (*StartAuthenticationResp) ProtoMessage()    {}
func (*StartAuthenticationResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_61c7956abb761639, []int{16}
}

func (m *StartAuthenticationResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartAuthenticationResp.Unmarshal(m, b)
}
func (m *StartAuthenticationResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartAuthenticationResp.Marshal(b, m, deterministic)
}
func (m *StartAuthenticationResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartAuthenticationResp.Merge(m, src)
}
func (m *StartAuthenticationResp) XXX_Size() int {
	return xxx_messageInfo_StartAuthenticationResp.Size(m)
}
func (m *StartAuthenticationResp) XXX_DiscardUnknown() {
	xxx_messageInfo_StartAuthenticationResp.DiscardUnknown(m)
}

var xxx_messageInfo_StartAuthenticationResp proto.InternalMessageInfo

func (m *StartAuthenticationResp) GetVerificationDirections() map[string]string {
	if m != nil {
		return m.VerificationDirections
	}
	return nil
}

type VerifyResp struct {
	VerifyStatus         bool     `protobuf:"varint,1,opt,name=VerifyStatus,proto3" json:"VerifyStatus,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VerifyResp) Reset()         { *m = VerifyResp{} }
func (m *VerifyResp) String() string { return proto.CompactTextString(m) }
func (*VerifyResp) ProtoMessage()    {}
func (*VerifyResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_61c7956abb761639, []int{17}
}

func (m *VerifyResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyResp.Unmarshal(m, b)
}
func (m *VerifyResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyResp.Marshal(b, m, deterministic)
}
func (m *VerifyResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyResp.Merge(m, src)
}
func (m *VerifyResp) XXX_Size() int {
	return xxx_messageInfo_VerifyResp.Size(m)
}
func (m *VerifyResp) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyResp.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyResp proto.InternalMessageInfo

func (m *VerifyResp) GetVerifyStatus() bool {
	if m != nil {
		return m.VerifyStatus
	}
	return false
}

///// Support types
type VerifierDetails struct {
	Name                 string   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	IdentityName         string   `protobuf:"bytes,2,opt,name=IdentityName,proto3" json:"IdentityName,omitempty"`
	SupportRegular       bool     `protobuf:"varint,3,opt,name=SupportRegular,proto3" json:"SupportRegular,omitempty"`
	SupportReverse       bool     `protobuf:"varint,4,opt,name=SupportReverse,proto3" json:"SupportReverse,omitempty"`
	SupportOAuth2        bool     `protobuf:"varint,5,opt,name=SupportOAuth2,proto3" json:"SupportOAuth2,omitempty"`
	SupportStatic        bool     `protobuf:"varint,6,opt,name=SupportStatic,proto3" json:"SupportStatic,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VerifierDetails) Reset()         { *m = VerifierDetails{} }
func (m *VerifierDetails) String() string { return proto.CompactTextString(m) }
func (*VerifierDetails) ProtoMessage()    {}
func (*VerifierDetails) Descriptor() ([]byte, []int) {
	return fileDescriptor_61c7956abb761639, []int{18}
}

func (m *VerifierDetails) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifierDetails.Unmarshal(m, b)
}
func (m *VerifierDetails) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifierDetails.Marshal(b, m, deterministic)
}
func (m *VerifierDetails) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifierDetails.Merge(m, src)
}
func (m *VerifierDetails) XXX_Size() int {
	return xxx_messageInfo_VerifierDetails.Size(m)
}
func (m *VerifierDetails) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifierDetails.DiscardUnknown(m)
}

var xxx_messageInfo_VerifierDetails proto.InternalMessageInfo

func (m *VerifierDetails) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *VerifierDetails) GetIdentityName() string {
	if m != nil {
		return m.IdentityName
	}
	return ""
}

func (m *VerifierDetails) GetSupportRegular() bool {
	if m != nil {
		return m.SupportRegular
	}
	return false
}

func (m *VerifierDetails) GetSupportReverse() bool {
	if m != nil {
		return m.SupportReverse
	}
	return false
}

func (m *VerifierDetails) GetSupportOAuth2() bool {
	if m != nil {
		return m.SupportOAuth2
	}
	return false
}

func (m *VerifierDetails) GetSupportStatic() bool {
	if m != nil {
		return m.SupportStatic
	}
	return false
}

type IdentityData struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Identity             string   `protobuf:"bytes,2,opt,name=identity,proto3" json:"identity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IdentityData) Reset()         { *m = IdentityData{} }
func (m *IdentityData) String() string { return proto.CompactTextString(m) }
func (*IdentityData) ProtoMessage()    {}
func (*IdentityData) Descriptor() ([]byte, []int) {
	return fileDescriptor_61c7956abb761639, []int{19}
}

func (m *IdentityData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IdentityData.Unmarshal(m, b)
}
func (m *IdentityData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IdentityData.Marshal(b, m, deterministic)
}
func (m *IdentityData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IdentityData.Merge(m, src)
}
func (m *IdentityData) XXX_Size() int {
	return xxx_messageInfo_IdentityData.Size(m)
}
func (m *IdentityData) XXX_DiscardUnknown() {
	xxx_messageInfo_IdentityData.DiscardUnknown(m)
}

var xxx_messageInfo_IdentityData proto.InternalMessageInfo

func (m *IdentityData) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *IdentityData) GetIdentity() string {
	if m != nil {
		return m.Identity
	}
	return ""
}

type UserDetails struct {
	ID                   string          `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Identities           []*IdentityData `protobuf:"bytes,2,rep,name=identities,proto3" json:"identities,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *UserDetails) Reset()         { *m = UserDetails{} }
func (m *UserDetails) String() string { return proto.CompactTextString(m) }
func (*UserDetails) ProtoMessage()    {}
func (*UserDetails) Descriptor() ([]byte, []int) {
	return fileDescriptor_61c7956abb761639, []int{20}
}

func (m *UserDetails) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserDetails.Unmarshal(m, b)
}
func (m *UserDetails) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserDetails.Marshal(b, m, deterministic)
}
func (m *UserDetails) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserDetails.Merge(m, src)
}
func (m *UserDetails) XXX_Size() int {
	return xxx_messageInfo_UserDetails.Size(m)
}
func (m *UserDetails) XXX_DiscardUnknown() {
	xxx_messageInfo_UserDetails.DiscardUnknown(m)
}

var xxx_messageInfo_UserDetails proto.InternalMessageInfo

func (m *UserDetails) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *UserDetails) GetIdentities() []*IdentityData {
	if m != nil {
		return m.Identities
	}
	return nil
}

type LoginAsReq struct {
	User                 string   `protobuf:"bytes,1,opt,name=User,proto3" json:"User,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginAsReq) Reset()         { *m = LoginAsReq{} }
func (m *LoginAsReq) String() string { return proto.CompactTextString(m) }
func (*LoginAsReq) ProtoMessage()    {}
func (*LoginAsReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_61c7956abb761639, []int{21}
}

func (m *LoginAsReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginAsReq.Unmarshal(m, b)
}
func (m *LoginAsReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginAsReq.Marshal(b, m, deterministic)
}
func (m *LoginAsReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginAsReq.Merge(m, src)
}
func (m *LoginAsReq) XXX_Size() int {
	return xxx_messageInfo_LoginAsReq.Size(m)
}
func (m *LoginAsReq) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginAsReq.DiscardUnknown(m)
}

var xxx_messageInfo_LoginAsReq proto.InternalMessageInfo

func (m *LoginAsReq) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

type LoginAsResp struct {
	Session              string   `protobuf:"bytes,1,opt,name=Session,proto3" json:"Session,omitempty"`
	User                 string   `protobuf:"bytes,2,opt,name=User,proto3" json:"User,omitempty"`
	Error                string   `protobuf:"bytes,3,opt,name=Error,proto3" json:"Error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginAsResp) Reset()         { *m = LoginAsResp{} }
func (m *LoginAsResp) String() string { return proto.CompactTextString(m) }
func (*LoginAsResp) ProtoMessage()    {}
func (*LoginAsResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_61c7956abb761639, []int{22}
}

func (m *LoginAsResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginAsResp.Unmarshal(m, b)
}
func (m *LoginAsResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginAsResp.Marshal(b, m, deterministic)
}
func (m *LoginAsResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginAsResp.Merge(m, src)
}
func (m *LoginAsResp) XXX_Size() int {
	return xxx_messageInfo_LoginAsResp.Size(m)
}
func (m *LoginAsResp) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginAsResp.DiscardUnknown(m)
}

var xxx_messageInfo_LoginAsResp proto.InternalMessageInfo

func (m *LoginAsResp) GetSession() string {
	if m != nil {
		return m.Session
	}
	return ""
}

func (m *LoginAsResp) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *LoginAsResp) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func init() {
	proto.RegisterType((*Dummy)(nil), "api.themakers.identity.Dummy")
	proto.RegisterType((*VerifiersDetailsRequest)(nil), "api.themakers.identity.VerifiersDetailsRequest")
	proto.RegisterType((*VerifierDetailsResponse)(nil), "api.themakers.identity.VerifierDetailsResponse")
	proto.RegisterType((*MyVerifiersDetailRequest)(nil), "api.themakers.identity.MyVerifiersDetailRequest")
	proto.RegisterType((*StartVerificationReq)(nil), "api.themakers.identity.StartVerificationReq")
	proto.RegisterMapType((map[string][]byte)(nil), "api.themakers.identity.StartVerificationReq.VerificationDataEntry")
	proto.RegisterType((*StartVerificationResp)(nil), "api.themakers.identity.StartVerificationResp")
	proto.RegisterType((*StatusReq)(nil), "api.themakers.identity.StatusReq")
	proto.RegisterType((*Status)(nil), "api.themakers.identity.Status")
	proto.RegisterType((*UserMergeReq)(nil), "api.themakers.identity.UserMergeReq")
	proto.RegisterType((*UserMergeResp)(nil), "api.themakers.identity.UserMergeResp")
	proto.RegisterType((*CancelAuthenticationReq)(nil), "api.themakers.identity.CancelAuthenticationReq")
	proto.RegisterType((*LogoutReq)(nil), "api.themakers.identity.LogoutReq")
	proto.RegisterType((*InitializeStaticVerifierReq)(nil), "api.themakers.identity.InitializeStaticVerifierReq")
	proto.RegisterMapType((map[string][]byte)(nil), "api.themakers.identity.InitializeStaticVerifierReq.InitalizationDataEntry")
	proto.RegisterType((*InitializeStaticVerifierResp)(nil), "api.themakers.identity.InitializeStaticVerifierResp")
	proto.RegisterType((*StartAuthenticationReq)(nil), "api.themakers.identity.StartAuthenticationReq")
	proto.RegisterType((*VerifyReq)(nil), "api.themakers.identity.VerifyReq")
	proto.RegisterType((*StartAuthenticationResp)(nil), "api.themakers.identity.StartAuthenticationResp")
	proto.RegisterMapType((map[string]string)(nil), "api.themakers.identity.StartAuthenticationResp.VerificationDirectionsEntry")
	proto.RegisterType((*VerifyResp)(nil), "api.themakers.identity.VerifyResp")
	proto.RegisterType((*VerifierDetails)(nil), "api.themakers.identity.VerifierDetails")
	proto.RegisterType((*IdentityData)(nil), "api.themakers.identity.IdentityData")
	proto.RegisterType((*UserDetails)(nil), "api.themakers.identity.UserDetails")
	proto.RegisterType((*LoginAsReq)(nil), "api.themakers.identity.LoginAsReq")
	proto.RegisterType((*LoginAsResp)(nil), "api.themakers.identity.LoginAsResp")
}

func init() { proto.RegisterFile("identity.proto", fileDescriptor_61c7956abb761639) }

var fileDescriptor_61c7956abb761639 = []byte{
	// 1020 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x57, 0x5f, 0x6f, 0xe3, 0x44,
	0x10, 0x97, 0x9d, 0x6b, 0x9a, 0x4c, 0x7a, 0x6d, 0x6f, 0xe9, 0xf5, 0x8c, 0xaf, 0x42, 0x61, 0x39,
	0xa0, 0x42, 0x9c, 0xef, 0x94, 0xe3, 0x01, 0xf1, 0x80, 0xd4, 0x6b, 0x8a, 0x14, 0xae, 0xe5, 0x0e,
	0x57, 0x20, 0x74, 0x2f, 0xc8, 0xa4, 0x4b, 0xba, 0x6a, 0x62, 0xbb, 0xbb, 0xeb, 0x0a, 0xf3, 0x80,
	0x54, 0x21, 0x24, 0x24, 0x3e, 0x02, 0x2f, 0xbc, 0xf1, 0x01, 0xf8, 0x4c, 0xbc, 0xf0, 0x29, 0xd0,
	0x7a, 0xd7, 0x8e, 0xff, 0xe6, 0x0f, 0x0f, 0x3c, 0xc5, 0x3b, 0x3b, 0x3b, 0xf3, 0xdb, 0x99, 0xd9,
	0xdf, 0x4c, 0x60, 0x9b, 0x5e, 0x10, 0x5f, 0x50, 0x11, 0x3b, 0x21, 0x0b, 0x44, 0x80, 0xf6, 0xbd,
	0x90, 0x3a, 0xe2, 0x92, 0xcc, 0xbc, 0x2b, 0xc2, 0xb8, 0x93, 0xee, 0xe2, 0x4d, 0xd8, 0x18, 0x46,
	0xb3, 0x59, 0x8c, 0xdf, 0x84, 0x07, 0x5f, 0x13, 0x46, 0xbf, 0xa7, 0x84, 0xf1, 0x21, 0x11, 0x1e,
	0x9d, 0x72, 0x97, 0x5c, 0x47, 0x84, 0x0b, 0xfc, 0xab, 0x31, 0xdf, 0xcb, 0xb6, 0x78, 0x18, 0xf8,
	0x9c, 0xa0, 0xf7, 0x60, 0x7b, 0xa4, 0x6c, 0xd1, 0xf8, 0x0b, 0x6f, 0x46, 0xb8, 0x65, 0xf4, 0x5b,
	0x87, 0x5d, 0xb7, 0x24, 0x45, 0x27, 0xd0, 0xcd, 0xcc, 0x5b, 0x66, 0xbf, 0x75, 0xd8, 0x1b, 0xbc,
	0xef, 0xd4, 0x63, 0x72, 0xca, 0xbe, 0xe6, 0x27, 0xf1, 0x6b, 0xb0, 0xce, 0xe2, 0x12, 0x4e, 0x0d,
	0x13, 0xd9, 0xd0, 0xd1, 0x4e, 0x63, 0xcb, 0xe8, 0x1b, 0x87, 0x5d, 0x37, 0x5b, 0x23, 0x0c, 0x5b,
	0xe9, 0x29, 0x89, 0xc7, 0x32, 0x93, 0xfd, 0x82, 0x0c, 0xff, 0x66, 0xc2, 0xde, 0xb9, 0xf0, 0x98,
	0x50, 0xd2, 0xb1, 0x27, 0x68, 0xe0, 0xbb, 0xe4, 0xba, 0x72, 0xd8, 0xa8, 0x1e, 0x2e, 0x38, 0x37,
	0x4b, 0xce, 0x7d, 0xd8, 0xcd, 0x9b, 0x1c, 0x7a, 0xc2, 0xb3, 0x5a, 0x49, 0x08, 0x9e, 0x37, 0x85,
	0xa0, 0x0e, 0x87, 0x53, 0x36, 0x72, 0xe2, 0x0b, 0x16, 0xbb, 0x15, 0xdb, 0xf6, 0x31, 0xdc, 0xaf,
	0x55, 0x45, 0xbb, 0xd0, 0xba, 0x22, 0x69, 0x70, 0xe4, 0x27, 0xda, 0x83, 0x8d, 0x1b, 0x6f, 0x1a,
	0xa9, 0x80, 0x6c, 0xb9, 0x6a, 0xf1, 0x89, 0xf9, 0xb1, 0x81, 0xff, 0x34, 0xe0, 0x7e, 0x0d, 0x0a,
	0x1e, 0xae, 0x14, 0x8e, 0x0f, 0x8a, 0x57, 0x3e, 0x0e, 0x2e, 0xd2, 0x98, 0x57, 0xe4, 0x85, 0xd0,
	0xb5, 0xaa, 0x79, 0x4b, 0xbf, 0x13, 0x5f, 0x77, 0x94, 0xaf, 0xbc, 0x0c, 0xf7, 0xa0, 0x7b, 0x2e,
	0x3c, 0x11, 0xc9, 0x7a, 0xc5, 0x7f, 0x18, 0xd0, 0x56, 0x2b, 0xf4, 0x08, 0xee, 0x1e, 0x45, 0xe2,
	0x52, 0x6a, 0x8e, 0x3d, 0x41, 0x2e, 0x12, 0xa0, 0x1d, 0xb7, 0x28, 0x94, 0x05, 0x9c, 0x13, 0x50,
	0x7f, 0x92, 0xe0, 0xec, 0xb8, 0x25, 0xa9, 0xbc, 0x91, 0x4b, 0x66, 0x1e, 0xf5, 0xa9, 0x3f, 0xf9,
	0xcc, 0x1b, 0x8b, 0x80, 0xf1, 0x04, 0x6d, 0xcb, 0xad, 0xc8, 0xd1, 0x01, 0x74, 0xcf, 0x09, 0xe7,
	0x34, 0xf0, 0x47, 0x43, 0x0d, 0x79, 0x2e, 0xc0, 0xdb, 0xb0, 0xf5, 0x15, 0x27, 0xec, 0x8c, 0xb0,
	0x09, 0x91, 0x90, 0x77, 0xe0, 0x6e, 0x6e, 0xcd, 0x43, 0xf9, 0x14, 0x8f, 0x3d, 0x7f, 0x4c, 0xa6,
	0x79, 0x08, 0x49, 0x09, 0xe0, 0xc7, 0xd0, 0x3d, 0x0d, 0x26, 0x41, 0x24, 0x64, 0x5d, 0xf6, 0xa1,
	0x77, 0x34, 0x9d, 0x6a, 0xc3, 0x5c, 0x5f, 0x2f, 0x2f, 0xc2, 0xb7, 0x26, 0x3c, 0x1c, 0xf9, 0x54,
	0x50, 0x6f, 0x4a, 0x7f, 0x24, 0x32, 0x2e, 0x74, 0x9c, 0xe6, 0x69, 0xd5, 0xca, 0xfe, 0x01, 0xee,
	0x49, 0x13, 0xd2, 0xc2, 0xbc, 0x7c, 0xd5, 0x0b, 0xfe, 0xbc, 0xa9, 0x7c, 0x17, 0xf8, 0x74, 0x2a,
	0xc6, 0x54, 0x19, 0x57, 0x9d, 0xd8, 0x43, 0xd8, 0xaf, 0x57, 0x5e, 0xab, 0x90, 0x5d, 0x38, 0x68,
	0x86, 0xc3, 0x43, 0x34, 0x80, 0xbd, 0x6c, 0x3f, 0x2d, 0xf2, 0x68, 0x2a, 0x12, 0xe3, 0x5b, 0x6e,
	0xed, 0x1e, 0xb6, 0x60, 0x3f, 0x79, 0x1b, 0xd5, 0x04, 0xfd, 0x6e, 0x68, 0xa2, 0x8b, 0x57, 0x8d,
	0xef, 0xff, 0xf9, 0x54, 0xfe, 0x31, 0xe0, 0x41, 0x2d, 0x70, 0x1e, 0xa2, 0x9f, 0x0d, 0xd8, 0x2f,
	0xd0, 0x06, 0x65, 0x64, 0x2c, 0x74, 0x65, 0xc9, 0x6c, 0xbf, 0x58, 0x48, 0x56, 0x55, 0x8b, 0x4e,
	0xbd, 0x35, 0x95, 0xee, 0x06, 0x57, 0xf6, 0x08, 0x1e, 0x2e, 0x38, 0xb6, 0x2c, 0xf1, 0xdd, 0x7c,
	0xe2, 0x9f, 0x02, 0xa4, 0x99, 0xc8, 0xb1, 0x56, 0xac, 0xd8, 0x41, 0xbf, 0x96, 0x82, 0x0c, 0xff,
	0x6d, 0xc0, 0x4e, 0xa9, 0xf9, 0x20, 0x04, 0x77, 0x72, 0xa9, 0x4b, 0xbe, 0x2b, 0xa1, 0x36, 0xab,
	0xa1, 0x96, 0xbc, 0x72, 0x1e, 0x85, 0x61, 0xc0, 0x84, 0x4b, 0x26, 0xd1, 0xd4, 0x63, 0x49, 0xc2,
	0x3a, 0x6e, 0x49, 0x5a, 0xd0, 0xbb, 0x21, 0x8c, 0xab, 0xc4, 0xe5, 0xf5, 0x12, 0xa9, 0x64, 0x33,
	0x2d, 0x79, 0x29, 0x43, 0x3d, 0xb0, 0x36, 0x14, 0x9b, 0x15, 0x84, 0x39, 0x2d, 0x55, 0xe9, 0x56,
	0xbb, 0xa0, 0xa5, 0x84, 0xf8, 0xd3, 0x39, 0x7e, 0xf9, 0xa6, 0xe4, 0x1d, 0xfd, 0xdc, 0x1d, 0x7d,
	0xdd, 0xd0, 0x68, 0xa9, 0xa1, 0x65, 0x43, 0xc3, 0x18, 0x7a, 0x92, 0xb1, 0xd2, 0x10, 0x6d, 0x83,
	0x39, 0x1a, 0xea, 0xc3, 0xe6, 0x68, 0x88, 0x86, 0x00, 0x5a, 0x95, 0x92, 0xb4, 0xd9, 0x3f, 0x6a,
	0xa4, 0x8a, 0x1c, 0x10, 0x37, 0x77, 0x0e, 0xf7, 0x01, 0x4e, 0x83, 0x09, 0xf5, 0x8f, 0x24, 0xaf,
	0x4b, 0x88, 0xd2, 0x65, 0x0a, 0x51, 0x7e, 0xe3, 0x2f, 0xa1, 0x97, 0x69, 0xf0, 0x10, 0x59, 0xb0,
	0xa9, 0x89, 0x4f, 0x6b, 0xa5, 0xcb, 0xec, 0xb0, 0x39, 0x3f, 0x2c, 0xeb, 0xe6, 0x84, 0xb1, 0x80,
	0xe9, 0x77, 0xa4, 0x16, 0x83, 0xbf, 0x3a, 0xf3, 0x17, 0x86, 0x7e, 0x02, 0xfb, 0x94, 0x72, 0x31,
	0xca, 0x30, 0x1d, 0xf9, 0x17, 0xd9, 0xec, 0x81, 0x9e, 0x2c, 0x1b, 0x5f, 0x4a, 0x63, 0x94, 0xfd,
	0x64, 0xd5, 0x79, 0x27, 0x9d, 0xad, 0x6e, 0x0d, 0x38, 0x90, 0x00, 0xce, 0xe2, 0x06, 0x08, 0x4f,
	0x9b, 0x2c, 0x36, 0xcd, 0x48, 0xeb, 0x63, 0x78, 0x05, 0xbd, 0xe3, 0x4b, 0x32, 0xbe, 0xd2, 0x3d,
	0xf5, 0xed, 0x05, 0x1c, 0xa0, 0x3a, 0xb0, 0xfd, 0xd6, 0x62, 0x15, 0x34, 0x81, 0xbd, 0xba, 0xee,
	0xd6, 0x1c, 0xcf, 0x86, 0x5e, 0xb8, 0xd4, 0xd1, 0x2f, 0x06, 0x58, 0x4d, 0xcc, 0x8f, 0x9e, 0xfd,
	0x87, 0xd6, 0x65, 0x7f, 0xb4, 0xfe, 0x21, 0x1e, 0xa2, 0x1b, 0x78, 0xa3, 0x86, 0x21, 0x91, 0xb3,
	0x16, 0x9d, 0x5e, 0x37, 0xa7, 0xae, 0x89, 0xd0, 0x43, 0xb8, 0x57, 0x19, 0xe0, 0xd0, 0x87, 0xeb,
	0x4c, 0x9c, 0xf6, 0xe3, 0x35, 0xb4, 0x79, 0x88, 0x5e, 0x42, 0x5b, 0xf1, 0x69, 0x73, 0x9d, 0x64,
	0xbd, 0xd1, 0xc6, 0xcb, 0x54, 0x78, 0x88, 0x5e, 0x40, 0x5b, 0x8d, 0x3b, 0xcd, 0x06, 0xb3, 0x71,
	0x68, 0x69, 0x3d, 0x7c, 0x03, 0xdd, 0x6c, 0xce, 0x42, 0x8d, 0x7c, 0x94, 0x1f, 0xcd, 0xec, 0x77,
	0x57, 0xd0, 0xe2, 0xe1, 0x80, 0xc0, 0x4e, 0x4a, 0x1a, 0xaf, 0x18, 0xbd, 0xf1, 0x04, 0x41, 0x2e,
	0x6c, 0x6a, 0x6e, 0x42, 0x78, 0x01, 0x74, 0x4d, 0x6f, 0xf6, 0x3b, 0x4b, 0x75, 0x78, 0xf8, 0x7c,
	0xf7, 0x75, 0xf6, 0xaf, 0xee, 0xdb, 0xe4, 0x5f, 0xdd, 0x77, 0xed, 0xe4, 0xe7, 0xd9, 0xbf, 0x01,
	0x00, 0x00, 0xff, 0xff, 0x85, 0xee, 0xf7, 0xba, 0xee, 0x0d, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// IdentityClient is the client API for Identity service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type IdentityClient interface {
	//method for give identities and verifiers for server
	ListIdentitiesAndVerifiers(ctx context.Context, in *VerifiersDetailsRequest, opts ...grpc.CallOption) (*VerifierDetailsResponse, error)
	//method for give identities and verifiers for user
	ListMyIdentitiesAndVerifiers(ctx context.Context, in *MyVerifiersDetailRequest, opts ...grpc.CallOption) (*VerifierDetailsResponse, error)
	CheckStatus(ctx context.Context, in *StatusReq, opts ...grpc.CallOption) (*Status, error)
	CancelAuthentication(ctx context.Context, in *CancelAuthenticationReq, opts ...grpc.CallOption) (*Status, error)
	InitializeStaticVerifier(ctx context.Context, in *InitializeStaticVerifierReq, opts ...grpc.CallOption) (*InitializeStaticVerifierResp, error)
	StartAuthentication(ctx context.Context, in *StartAuthenticationReq, opts ...grpc.CallOption) (*StartAuthenticationResp, error)
	StartVerification(ctx context.Context, in *StartVerificationReq, opts ...grpc.CallOption) (*StartVerificationResp, error)
	Verify(ctx context.Context, in *VerifyReq, opts ...grpc.CallOption) (*VerifyResp, error)
	Logout(ctx context.Context, in *LogoutReq, opts ...grpc.CallOption) (*Status, error)
	UserMerge(ctx context.Context, in *UserMergeReq, opts ...grpc.CallOption) (*UserMergeResp, error)
}

type identityClient struct {
	cc *grpc.ClientConn
}

func NewIdentityClient(cc *grpc.ClientConn) IdentityClient {
	return &identityClient{cc}
}

func (c *identityClient) ListIdentitiesAndVerifiers(ctx context.Context, in *VerifiersDetailsRequest, opts ...grpc.CallOption) (*VerifierDetailsResponse, error) {
	out := new(VerifierDetailsResponse)
	err := c.cc.Invoke(ctx, "/api.themakers.identity.Identity/ListIdentitiesAndVerifiers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityClient) ListMyIdentitiesAndVerifiers(ctx context.Context, in *MyVerifiersDetailRequest, opts ...grpc.CallOption) (*VerifierDetailsResponse, error) {
	out := new(VerifierDetailsResponse)
	err := c.cc.Invoke(ctx, "/api.themakers.identity.Identity/ListMyIdentitiesAndVerifiers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityClient) CheckStatus(ctx context.Context, in *StatusReq, opts ...grpc.CallOption) (*Status, error) {
	out := new(Status)
	err := c.cc.Invoke(ctx, "/api.themakers.identity.Identity/CheckStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityClient) CancelAuthentication(ctx context.Context, in *CancelAuthenticationReq, opts ...grpc.CallOption) (*Status, error) {
	out := new(Status)
	err := c.cc.Invoke(ctx, "/api.themakers.identity.Identity/CancelAuthentication", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityClient) InitializeStaticVerifier(ctx context.Context, in *InitializeStaticVerifierReq, opts ...grpc.CallOption) (*InitializeStaticVerifierResp, error) {
	out := new(InitializeStaticVerifierResp)
	err := c.cc.Invoke(ctx, "/api.themakers.identity.Identity/InitializeStaticVerifier", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityClient) StartAuthentication(ctx context.Context, in *StartAuthenticationReq, opts ...grpc.CallOption) (*StartAuthenticationResp, error) {
	out := new(StartAuthenticationResp)
	err := c.cc.Invoke(ctx, "/api.themakers.identity.Identity/StartAuthentication", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityClient) StartVerification(ctx context.Context, in *StartVerificationReq, opts ...grpc.CallOption) (*StartVerificationResp, error) {
	out := new(StartVerificationResp)
	err := c.cc.Invoke(ctx, "/api.themakers.identity.Identity/StartVerification", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityClient) Verify(ctx context.Context, in *VerifyReq, opts ...grpc.CallOption) (*VerifyResp, error) {
	out := new(VerifyResp)
	err := c.cc.Invoke(ctx, "/api.themakers.identity.Identity/Verify", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityClient) Logout(ctx context.Context, in *LogoutReq, opts ...grpc.CallOption) (*Status, error) {
	out := new(Status)
	err := c.cc.Invoke(ctx, "/api.themakers.identity.Identity/Logout", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityClient) UserMerge(ctx context.Context, in *UserMergeReq, opts ...grpc.CallOption) (*UserMergeResp, error) {
	out := new(UserMergeResp)
	err := c.cc.Invoke(ctx, "/api.themakers.identity.Identity/UserMerge", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IdentityServer is the server API for Identity service.
type IdentityServer interface {
	//method for give identities and verifiers for server
	ListIdentitiesAndVerifiers(context.Context, *VerifiersDetailsRequest) (*VerifierDetailsResponse, error)
	//method for give identities and verifiers for user
	ListMyIdentitiesAndVerifiers(context.Context, *MyVerifiersDetailRequest) (*VerifierDetailsResponse, error)
	CheckStatus(context.Context, *StatusReq) (*Status, error)
	CancelAuthentication(context.Context, *CancelAuthenticationReq) (*Status, error)
	InitializeStaticVerifier(context.Context, *InitializeStaticVerifierReq) (*InitializeStaticVerifierResp, error)
	StartAuthentication(context.Context, *StartAuthenticationReq) (*StartAuthenticationResp, error)
	StartVerification(context.Context, *StartVerificationReq) (*StartVerificationResp, error)
	Verify(context.Context, *VerifyReq) (*VerifyResp, error)
	Logout(context.Context, *LogoutReq) (*Status, error)
	UserMerge(context.Context, *UserMergeReq) (*UserMergeResp, error)
}

// UnimplementedIdentityServer can be embedded to have forward compatible implementations.
type UnimplementedIdentityServer struct {
}

func (*UnimplementedIdentityServer) ListIdentitiesAndVerifiers(ctx context.Context, req *VerifiersDetailsRequest) (*VerifierDetailsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListIdentitiesAndVerifiers not implemented")
}
func (*UnimplementedIdentityServer) ListMyIdentitiesAndVerifiers(ctx context.Context, req *MyVerifiersDetailRequest) (*VerifierDetailsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListMyIdentitiesAndVerifiers not implemented")
}
func (*UnimplementedIdentityServer) CheckStatus(ctx context.Context, req *StatusReq) (*Status, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckStatus not implemented")
}
func (*UnimplementedIdentityServer) CancelAuthentication(ctx context.Context, req *CancelAuthenticationReq) (*Status, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelAuthentication not implemented")
}
func (*UnimplementedIdentityServer) InitializeStaticVerifier(ctx context.Context, req *InitializeStaticVerifierReq) (*InitializeStaticVerifierResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InitializeStaticVerifier not implemented")
}
func (*UnimplementedIdentityServer) StartAuthentication(ctx context.Context, req *StartAuthenticationReq) (*StartAuthenticationResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartAuthentication not implemented")
}
func (*UnimplementedIdentityServer) StartVerification(ctx context.Context, req *StartVerificationReq) (*StartVerificationResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartVerification not implemented")
}
func (*UnimplementedIdentityServer) Verify(ctx context.Context, req *VerifyReq) (*VerifyResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Verify not implemented")
}
func (*UnimplementedIdentityServer) Logout(ctx context.Context, req *LogoutReq) (*Status, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Logout not implemented")
}
func (*UnimplementedIdentityServer) UserMerge(ctx context.Context, req *UserMergeReq) (*UserMergeResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserMerge not implemented")
}

func RegisterIdentityServer(s *grpc.Server, srv IdentityServer) {
	s.RegisterService(&_Identity_serviceDesc, srv)
}

func _Identity_ListIdentitiesAndVerifiers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifiersDetailsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServer).ListIdentitiesAndVerifiers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.themakers.identity.Identity/ListIdentitiesAndVerifiers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServer).ListIdentitiesAndVerifiers(ctx, req.(*VerifiersDetailsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Identity_ListMyIdentitiesAndVerifiers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MyVerifiersDetailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServer).ListMyIdentitiesAndVerifiers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.themakers.identity.Identity/ListMyIdentitiesAndVerifiers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServer).ListMyIdentitiesAndVerifiers(ctx, req.(*MyVerifiersDetailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Identity_CheckStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServer).CheckStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.themakers.identity.Identity/CheckStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServer).CheckStatus(ctx, req.(*StatusReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Identity_CancelAuthentication_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelAuthenticationReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServer).CancelAuthentication(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.themakers.identity.Identity/CancelAuthentication",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServer).CancelAuthentication(ctx, req.(*CancelAuthenticationReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Identity_InitializeStaticVerifier_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitializeStaticVerifierReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServer).InitializeStaticVerifier(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.themakers.identity.Identity/InitializeStaticVerifier",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServer).InitializeStaticVerifier(ctx, req.(*InitializeStaticVerifierReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Identity_StartAuthentication_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartAuthenticationReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServer).StartAuthentication(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.themakers.identity.Identity/StartAuthentication",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServer).StartAuthentication(ctx, req.(*StartAuthenticationReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Identity_StartVerification_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartVerificationReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServer).StartVerification(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.themakers.identity.Identity/StartVerification",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServer).StartVerification(ctx, req.(*StartVerificationReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Identity_Verify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServer).Verify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.themakers.identity.Identity/Verify",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServer).Verify(ctx, req.(*VerifyReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Identity_Logout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogoutReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServer).Logout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.themakers.identity.Identity/Logout",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServer).Logout(ctx, req.(*LogoutReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Identity_UserMerge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserMergeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServer).UserMerge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.themakers.identity.Identity/UserMerge",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServer).UserMerge(ctx, req.(*UserMergeReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Identity_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.themakers.identity.Identity",
	HandlerType: (*IdentityServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListIdentitiesAndVerifiers",
			Handler:    _Identity_ListIdentitiesAndVerifiers_Handler,
		},
		{
			MethodName: "ListMyIdentitiesAndVerifiers",
			Handler:    _Identity_ListMyIdentitiesAndVerifiers_Handler,
		},
		{
			MethodName: "CheckStatus",
			Handler:    _Identity_CheckStatus_Handler,
		},
		{
			MethodName: "CancelAuthentication",
			Handler:    _Identity_CancelAuthentication_Handler,
		},
		{
			MethodName: "InitializeStaticVerifier",
			Handler:    _Identity_InitializeStaticVerifier_Handler,
		},
		{
			MethodName: "StartAuthentication",
			Handler:    _Identity_StartAuthentication_Handler,
		},
		{
			MethodName: "StartVerification",
			Handler:    _Identity_StartVerification_Handler,
		},
		{
			MethodName: "Verify",
			Handler:    _Identity_Verify_Handler,
		},
		{
			MethodName: "Logout",
			Handler:    _Identity_Logout_Handler,
		},
		{
			MethodName: "UserMerge",
			Handler:    _Identity_UserMerge_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "identity.proto",
}

// IdentityPrivateClient is the client API for IdentityPrivate service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type IdentityPrivateClient interface {
	LoginAs(ctx context.Context, in *LoginAsReq, opts ...grpc.CallOption) (*LoginAsResp, error)
}

type identityPrivateClient struct {
	cc *grpc.ClientConn
}

func NewIdentityPrivateClient(cc *grpc.ClientConn) IdentityPrivateClient {
	return &identityPrivateClient{cc}
}

func (c *identityPrivateClient) LoginAs(ctx context.Context, in *LoginAsReq, opts ...grpc.CallOption) (*LoginAsResp, error) {
	out := new(LoginAsResp)
	err := c.cc.Invoke(ctx, "/api.themakers.identity.IdentityPrivate/LoginAs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IdentityPrivateServer is the server API for IdentityPrivate service.
type IdentityPrivateServer interface {
	LoginAs(context.Context, *LoginAsReq) (*LoginAsResp, error)
}

// UnimplementedIdentityPrivateServer can be embedded to have forward compatible implementations.
type UnimplementedIdentityPrivateServer struct {
}

func (*UnimplementedIdentityPrivateServer) LoginAs(ctx context.Context, req *LoginAsReq) (*LoginAsResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoginAs not implemented")
}

func RegisterIdentityPrivateServer(s *grpc.Server, srv IdentityPrivateServer) {
	s.RegisterService(&_IdentityPrivate_serviceDesc, srv)
}

func _IdentityPrivate_LoginAs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginAsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityPrivateServer).LoginAs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.themakers.identity.IdentityPrivate/LoginAs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityPrivateServer).LoginAs(ctx, req.(*LoginAsReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _IdentityPrivate_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.themakers.identity.IdentityPrivate",
	HandlerType: (*IdentityPrivateServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "LoginAs",
			Handler:    _IdentityPrivate_LoginAs_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "identity.proto",
}
