// Code generated by protoc-gen-go. DO NOT EDIT.
// source: identity.proto

package identity_proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Dummy struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Dummy) Reset()         { *m = Dummy{} }
func (m *Dummy) String() string { return proto.CompactTextString(m) }
func (*Dummy) ProtoMessage()    {}
func (*Dummy) Descriptor() ([]byte, []int) {
	return fileDescriptor_identity_1b3b7dff4977fe50, []int{0}
}
func (m *Dummy) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Dummy.Unmarshal(m, b)
}
func (m *Dummy) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Dummy.Marshal(b, m, deterministic)
}
func (dst *Dummy) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Dummy.Merge(dst, src)
}
func (m *Dummy) XXX_Size() int {
	return xxx_messageInfo_Dummy.Size(m)
}
func (m *Dummy) XXX_DiscardUnknown() {
	xxx_messageInfo_Dummy.DiscardUnknown(m)
}

var xxx_messageInfo_Dummy proto.InternalMessageInfo

type ProviderDetailsReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProviderDetailsReq) Reset()         { *m = ProviderDetailsReq{} }
func (m *ProviderDetailsReq) String() string { return proto.CompactTextString(m) }
func (*ProviderDetailsReq) ProtoMessage()    {}
func (*ProviderDetailsReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_identity_1b3b7dff4977fe50, []int{1}
}
func (m *ProviderDetailsReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProviderDetailsReq.Unmarshal(m, b)
}
func (m *ProviderDetailsReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProviderDetailsReq.Marshal(b, m, deterministic)
}
func (dst *ProviderDetailsReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProviderDetailsReq.Merge(dst, src)
}
func (m *ProviderDetailsReq) XXX_Size() int {
	return xxx_messageInfo_ProviderDetailsReq.Size(m)
}
func (m *ProviderDetailsReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ProviderDetailsReq.DiscardUnknown(m)
}

var xxx_messageInfo_ProviderDetailsReq proto.InternalMessageInfo

type ProviderDetailsResp struct {
	Providers            []*ProviderDetails `protobuf:"bytes,1,rep,name=Providers,proto3" json:"Providers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *ProviderDetailsResp) Reset()         { *m = ProviderDetailsResp{} }
func (m *ProviderDetailsResp) String() string { return proto.CompactTextString(m) }
func (*ProviderDetailsResp) ProtoMessage()    {}
func (*ProviderDetailsResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_identity_1b3b7dff4977fe50, []int{2}
}
func (m *ProviderDetailsResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProviderDetailsResp.Unmarshal(m, b)
}
func (m *ProviderDetailsResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProviderDetailsResp.Marshal(b, m, deterministic)
}
func (dst *ProviderDetailsResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProviderDetailsResp.Merge(dst, src)
}
func (m *ProviderDetailsResp) XXX_Size() int {
	return xxx_messageInfo_ProviderDetailsResp.Size(m)
}
func (m *ProviderDetailsResp) XXX_DiscardUnknown() {
	xxx_messageInfo_ProviderDetailsResp.DiscardUnknown(m)
}

var xxx_messageInfo_ProviderDetailsResp proto.InternalMessageInfo

func (m *ProviderDetailsResp) GetProviders() []*ProviderDetails {
	if m != nil {
		return m.Providers
	}
	return nil
}

type ProviderDetails struct {
	Name                 string   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	SupportType1         bool     `protobuf:"varint,2,opt,name=SupportType1,proto3" json:"SupportType1,omitempty"`
	SupportType2         bool     `protobuf:"varint,3,opt,name=SupportType2,proto3" json:"SupportType2,omitempty"`
	SupportOAuth2        bool     `protobuf:"varint,4,opt,name=SupportOAuth2,proto3" json:"SupportOAuth2,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProviderDetails) Reset()         { *m = ProviderDetails{} }
func (m *ProviderDetails) String() string { return proto.CompactTextString(m) }
func (*ProviderDetails) ProtoMessage()    {}
func (*ProviderDetails) Descriptor() ([]byte, []int) {
	return fileDescriptor_identity_1b3b7dff4977fe50, []int{3}
}
func (m *ProviderDetails) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProviderDetails.Unmarshal(m, b)
}
func (m *ProviderDetails) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProviderDetails.Marshal(b, m, deterministic)
}
func (dst *ProviderDetails) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProviderDetails.Merge(dst, src)
}
func (m *ProviderDetails) XXX_Size() int {
	return xxx_messageInfo_ProviderDetails.Size(m)
}
func (m *ProviderDetails) XXX_DiscardUnknown() {
	xxx_messageInfo_ProviderDetails.DiscardUnknown(m)
}

var xxx_messageInfo_ProviderDetails proto.InternalMessageInfo

func (m *ProviderDetails) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ProviderDetails) GetSupportType1() bool {
	if m != nil {
		return m.SupportType1
	}
	return false
}

func (m *ProviderDetails) GetSupportType2() bool {
	if m != nil {
		return m.SupportType2
	}
	return false
}

func (m *ProviderDetails) GetSupportOAuth2() bool {
	if m != nil {
		return m.SupportOAuth2
	}
	return false
}

// //////////////////////////////////////////////////////////////
// // Type 1
// //
type Type1VerificationReq struct {
	Provider             string   `protobuf:"bytes,1,opt,name=Provider,proto3" json:"Provider,omitempty"`
	Identity             string   `protobuf:"bytes,2,opt,name=Identity,proto3" json:"Identity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Type1VerificationReq) Reset()         { *m = Type1VerificationReq{} }
func (m *Type1VerificationReq) String() string { return proto.CompactTextString(m) }
func (*Type1VerificationReq) ProtoMessage()    {}
func (*Type1VerificationReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_identity_1b3b7dff4977fe50, []int{4}
}
func (m *Type1VerificationReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Type1VerificationReq.Unmarshal(m, b)
}
func (m *Type1VerificationReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Type1VerificationReq.Marshal(b, m, deterministic)
}
func (dst *Type1VerificationReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Type1VerificationReq.Merge(dst, src)
}
func (m *Type1VerificationReq) XXX_Size() int {
	return xxx_messageInfo_Type1VerificationReq.Size(m)
}
func (m *Type1VerificationReq) XXX_DiscardUnknown() {
	xxx_messageInfo_Type1VerificationReq.DiscardUnknown(m)
}

var xxx_messageInfo_Type1VerificationReq proto.InternalMessageInfo

func (m *Type1VerificationReq) GetProvider() string {
	if m != nil {
		return m.Provider
	}
	return ""
}

func (m *Type1VerificationReq) GetIdentity() string {
	if m != nil {
		return m.Identity
	}
	return ""
}

type Type1VerificationDirections struct {
	VerificationID       string   `protobuf:"bytes,1,opt,name=VerificationID,proto3" json:"VerificationID,omitempty"`
	Target               string   `protobuf:"bytes,2,opt,name=Target,proto3" json:"Target,omitempty"`
	SecurityCode         string   `protobuf:"bytes,3,opt,name=SecurityCode,proto3" json:"SecurityCode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Type1VerificationDirections) Reset()         { *m = Type1VerificationDirections{} }
func (m *Type1VerificationDirections) String() string { return proto.CompactTextString(m) }
func (*Type1VerificationDirections) ProtoMessage()    {}
func (*Type1VerificationDirections) Descriptor() ([]byte, []int) {
	return fileDescriptor_identity_1b3b7dff4977fe50, []int{5}
}
func (m *Type1VerificationDirections) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Type1VerificationDirections.Unmarshal(m, b)
}
func (m *Type1VerificationDirections) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Type1VerificationDirections.Marshal(b, m, deterministic)
}
func (dst *Type1VerificationDirections) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Type1VerificationDirections.Merge(dst, src)
}
func (m *Type1VerificationDirections) XXX_Size() int {
	return xxx_messageInfo_Type1VerificationDirections.Size(m)
}
func (m *Type1VerificationDirections) XXX_DiscardUnknown() {
	xxx_messageInfo_Type1VerificationDirections.DiscardUnknown(m)
}

var xxx_messageInfo_Type1VerificationDirections proto.InternalMessageInfo

func (m *Type1VerificationDirections) GetVerificationID() string {
	if m != nil {
		return m.VerificationID
	}
	return ""
}

func (m *Type1VerificationDirections) GetTarget() string {
	if m != nil {
		return m.Target
	}
	return ""
}

func (m *Type1VerificationDirections) GetSecurityCode() string {
	if m != nil {
		return m.SecurityCode
	}
	return ""
}

type Type1ResultRequest struct {
	VerificationID       string   `protobuf:"bytes,1,opt,name=VerificationID,proto3" json:"VerificationID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Type1ResultRequest) Reset()         { *m = Type1ResultRequest{} }
func (m *Type1ResultRequest) String() string { return proto.CompactTextString(m) }
func (*Type1ResultRequest) ProtoMessage()    {}
func (*Type1ResultRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_identity_1b3b7dff4977fe50, []int{6}
}
func (m *Type1ResultRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Type1ResultRequest.Unmarshal(m, b)
}
func (m *Type1ResultRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Type1ResultRequest.Marshal(b, m, deterministic)
}
func (dst *Type1ResultRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Type1ResultRequest.Merge(dst, src)
}
func (m *Type1ResultRequest) XXX_Size() int {
	return xxx_messageInfo_Type1ResultRequest.Size(m)
}
func (m *Type1ResultRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_Type1ResultRequest.DiscardUnknown(m)
}

var xxx_messageInfo_Type1ResultRequest proto.InternalMessageInfo

func (m *Type1ResultRequest) GetVerificationID() string {
	if m != nil {
		return m.VerificationID
	}
	return ""
}

type Type1ResultResp struct {
	Session              string   `protobuf:"bytes,1,opt,name=Session,proto3" json:"Session,omitempty"`
	User                 string   `protobuf:"bytes,2,opt,name=User,proto3" json:"User,omitempty"`
	Error                string   `protobuf:"bytes,3,opt,name=Error,proto3" json:"Error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Type1ResultResp) Reset()         { *m = Type1ResultResp{} }
func (m *Type1ResultResp) String() string { return proto.CompactTextString(m) }
func (*Type1ResultResp) ProtoMessage()    {}
func (*Type1ResultResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_identity_1b3b7dff4977fe50, []int{7}
}
func (m *Type1ResultResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Type1ResultResp.Unmarshal(m, b)
}
func (m *Type1ResultResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Type1ResultResp.Marshal(b, m, deterministic)
}
func (dst *Type1ResultResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Type1ResultResp.Merge(dst, src)
}
func (m *Type1ResultResp) XXX_Size() int {
	return xxx_messageInfo_Type1ResultResp.Size(m)
}
func (m *Type1ResultResp) XXX_DiscardUnknown() {
	xxx_messageInfo_Type1ResultResp.DiscardUnknown(m)
}

var xxx_messageInfo_Type1ResultResp proto.InternalMessageInfo

func (m *Type1ResultResp) GetSession() string {
	if m != nil {
		return m.Session
	}
	return ""
}

func (m *Type1ResultResp) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *Type1ResultResp) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

// //////////////////////////////////////////////////////////////
// // Type 2
// //
type Type2VerificationReq struct {
	Provider             string   `protobuf:"bytes,1,opt,name=Provider,proto3" json:"Provider,omitempty"`
	Identity             string   `protobuf:"bytes,2,opt,name=Identity,proto3" json:"Identity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Type2VerificationReq) Reset()         { *m = Type2VerificationReq{} }
func (m *Type2VerificationReq) String() string { return proto.CompactTextString(m) }
func (*Type2VerificationReq) ProtoMessage()    {}
func (*Type2VerificationReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_identity_1b3b7dff4977fe50, []int{8}
}
func (m *Type2VerificationReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Type2VerificationReq.Unmarshal(m, b)
}
func (m *Type2VerificationReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Type2VerificationReq.Marshal(b, m, deterministic)
}
func (dst *Type2VerificationReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Type2VerificationReq.Merge(dst, src)
}
func (m *Type2VerificationReq) XXX_Size() int {
	return xxx_messageInfo_Type2VerificationReq.Size(m)
}
func (m *Type2VerificationReq) XXX_DiscardUnknown() {
	xxx_messageInfo_Type2VerificationReq.DiscardUnknown(m)
}

var xxx_messageInfo_Type2VerificationReq proto.InternalMessageInfo

func (m *Type2VerificationReq) GetProvider() string {
	if m != nil {
		return m.Provider
	}
	return ""
}

func (m *Type2VerificationReq) GetIdentity() string {
	if m != nil {
		return m.Identity
	}
	return ""
}

type Type2VerificationResp struct {
	VerificationID       string   `protobuf:"bytes,1,opt,name=VerificationID,proto3" json:"VerificationID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Type2VerificationResp) Reset()         { *m = Type2VerificationResp{} }
func (m *Type2VerificationResp) String() string { return proto.CompactTextString(m) }
func (*Type2VerificationResp) ProtoMessage()    {}
func (*Type2VerificationResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_identity_1b3b7dff4977fe50, []int{9}
}
func (m *Type2VerificationResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Type2VerificationResp.Unmarshal(m, b)
}
func (m *Type2VerificationResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Type2VerificationResp.Marshal(b, m, deterministic)
}
func (dst *Type2VerificationResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Type2VerificationResp.Merge(dst, src)
}
func (m *Type2VerificationResp) XXX_Size() int {
	return xxx_messageInfo_Type2VerificationResp.Size(m)
}
func (m *Type2VerificationResp) XXX_DiscardUnknown() {
	xxx_messageInfo_Type2VerificationResp.DiscardUnknown(m)
}

var xxx_messageInfo_Type2VerificationResp proto.InternalMessageInfo

func (m *Type2VerificationResp) GetVerificationID() string {
	if m != nil {
		return m.VerificationID
	}
	return ""
}

type Type2VerifyReq struct {
	VerificationID       string   `protobuf:"bytes,1,opt,name=VerificationID,proto3" json:"VerificationID,omitempty"`
	SecurityCode         string   `protobuf:"bytes,3,opt,name=SecurityCode,proto3" json:"SecurityCode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Type2VerifyReq) Reset()         { *m = Type2VerifyReq{} }
func (m *Type2VerifyReq) String() string { return proto.CompactTextString(m) }
func (*Type2VerifyReq) ProtoMessage()    {}
func (*Type2VerifyReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_identity_1b3b7dff4977fe50, []int{10}
}
func (m *Type2VerifyReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Type2VerifyReq.Unmarshal(m, b)
}
func (m *Type2VerifyReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Type2VerifyReq.Marshal(b, m, deterministic)
}
func (dst *Type2VerifyReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Type2VerifyReq.Merge(dst, src)
}
func (m *Type2VerifyReq) XXX_Size() int {
	return xxx_messageInfo_Type2VerifyReq.Size(m)
}
func (m *Type2VerifyReq) XXX_DiscardUnknown() {
	xxx_messageInfo_Type2VerifyReq.DiscardUnknown(m)
}

var xxx_messageInfo_Type2VerifyReq proto.InternalMessageInfo

func (m *Type2VerifyReq) GetVerificationID() string {
	if m != nil {
		return m.VerificationID
	}
	return ""
}

func (m *Type2VerifyReq) GetSecurityCode() string {
	if m != nil {
		return m.SecurityCode
	}
	return ""
}

type Type2ResultResp struct {
	Session              string   `protobuf:"bytes,1,opt,name=Session,proto3" json:"Session,omitempty"`
	User                 string   `protobuf:"bytes,2,opt,name=User,proto3" json:"User,omitempty"`
	Error                string   `protobuf:"bytes,3,opt,name=Error,proto3" json:"Error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Type2ResultResp) Reset()         { *m = Type2ResultResp{} }
func (m *Type2ResultResp) String() string { return proto.CompactTextString(m) }
func (*Type2ResultResp) ProtoMessage()    {}
func (*Type2ResultResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_identity_1b3b7dff4977fe50, []int{11}
}
func (m *Type2ResultResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Type2ResultResp.Unmarshal(m, b)
}
func (m *Type2ResultResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Type2ResultResp.Marshal(b, m, deterministic)
}
func (dst *Type2ResultResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Type2ResultResp.Merge(dst, src)
}
func (m *Type2ResultResp) XXX_Size() int {
	return xxx_messageInfo_Type2ResultResp.Size(m)
}
func (m *Type2ResultResp) XXX_DiscardUnknown() {
	xxx_messageInfo_Type2ResultResp.DiscardUnknown(m)
}

var xxx_messageInfo_Type2ResultResp proto.InternalMessageInfo

func (m *Type2ResultResp) GetSession() string {
	if m != nil {
		return m.Session
	}
	return ""
}

func (m *Type2ResultResp) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *Type2ResultResp) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type OAuth2Req struct {
	Provider             string   `protobuf:"bytes,1,opt,name=Provider,proto3" json:"Provider,omitempty"`
	Code                 string   `protobuf:"bytes,2,opt,name=Code,proto3" json:"Code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OAuth2Req) Reset()         { *m = OAuth2Req{} }
func (m *OAuth2Req) String() string { return proto.CompactTextString(m) }
func (*OAuth2Req) ProtoMessage()    {}
func (*OAuth2Req) Descriptor() ([]byte, []int) {
	return fileDescriptor_identity_1b3b7dff4977fe50, []int{12}
}
func (m *OAuth2Req) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OAuth2Req.Unmarshal(m, b)
}
func (m *OAuth2Req) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OAuth2Req.Marshal(b, m, deterministic)
}
func (dst *OAuth2Req) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OAuth2Req.Merge(dst, src)
}
func (m *OAuth2Req) XXX_Size() int {
	return xxx_messageInfo_OAuth2Req.Size(m)
}
func (m *OAuth2Req) XXX_DiscardUnknown() {
	xxx_messageInfo_OAuth2Req.DiscardUnknown(m)
}

var xxx_messageInfo_OAuth2Req proto.InternalMessageInfo

func (m *OAuth2Req) GetProvider() string {
	if m != nil {
		return m.Provider
	}
	return ""
}

func (m *OAuth2Req) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

type OAuth2VerifyResp struct {
	Session              string   `protobuf:"bytes,1,opt,name=Session,proto3" json:"Session,omitempty"`
	User                 string   `protobuf:"bytes,2,opt,name=User,proto3" json:"User,omitempty"`
	Error                string   `protobuf:"bytes,3,opt,name=Error,proto3" json:"Error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OAuth2VerifyResp) Reset()         { *m = OAuth2VerifyResp{} }
func (m *OAuth2VerifyResp) String() string { return proto.CompactTextString(m) }
func (*OAuth2VerifyResp) ProtoMessage()    {}
func (*OAuth2VerifyResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_identity_1b3b7dff4977fe50, []int{13}
}
func (m *OAuth2VerifyResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OAuth2VerifyResp.Unmarshal(m, b)
}
func (m *OAuth2VerifyResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OAuth2VerifyResp.Marshal(b, m, deterministic)
}
func (dst *OAuth2VerifyResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OAuth2VerifyResp.Merge(dst, src)
}
func (m *OAuth2VerifyResp) XXX_Size() int {
	return xxx_messageInfo_OAuth2VerifyResp.Size(m)
}
func (m *OAuth2VerifyResp) XXX_DiscardUnknown() {
	xxx_messageInfo_OAuth2VerifyResp.DiscardUnknown(m)
}

var xxx_messageInfo_OAuth2VerifyResp proto.InternalMessageInfo

func (m *OAuth2VerifyResp) GetSession() string {
	if m != nil {
		return m.Session
	}
	return ""
}

func (m *OAuth2VerifyResp) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *OAuth2VerifyResp) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type LoginAsReq struct {
	User                 string   `protobuf:"bytes,1,opt,name=User,proto3" json:"User,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginAsReq) Reset()         { *m = LoginAsReq{} }
func (m *LoginAsReq) String() string { return proto.CompactTextString(m) }
func (*LoginAsReq) ProtoMessage()    {}
func (*LoginAsReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_identity_1b3b7dff4977fe50, []int{14}
}
func (m *LoginAsReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginAsReq.Unmarshal(m, b)
}
func (m *LoginAsReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginAsReq.Marshal(b, m, deterministic)
}
func (dst *LoginAsReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginAsReq.Merge(dst, src)
}
func (m *LoginAsReq) XXX_Size() int {
	return xxx_messageInfo_LoginAsReq.Size(m)
}
func (m *LoginAsReq) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginAsReq.DiscardUnknown(m)
}

var xxx_messageInfo_LoginAsReq proto.InternalMessageInfo

func (m *LoginAsReq) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

type LoginAsResp struct {
	Session              string   `protobuf:"bytes,1,opt,name=Session,proto3" json:"Session,omitempty"`
	User                 string   `protobuf:"bytes,2,opt,name=User,proto3" json:"User,omitempty"`
	Error                string   `protobuf:"bytes,3,opt,name=Error,proto3" json:"Error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginAsResp) Reset()         { *m = LoginAsResp{} }
func (m *LoginAsResp) String() string { return proto.CompactTextString(m) }
func (*LoginAsResp) ProtoMessage()    {}
func (*LoginAsResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_identity_1b3b7dff4977fe50, []int{15}
}
func (m *LoginAsResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginAsResp.Unmarshal(m, b)
}
func (m *LoginAsResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginAsResp.Marshal(b, m, deterministic)
}
func (dst *LoginAsResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginAsResp.Merge(dst, src)
}
func (m *LoginAsResp) XXX_Size() int {
	return xxx_messageInfo_LoginAsResp.Size(m)
}
func (m *LoginAsResp) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginAsResp.DiscardUnknown(m)
}

var xxx_messageInfo_LoginAsResp proto.InternalMessageInfo

func (m *LoginAsResp) GetSession() string {
	if m != nil {
		return m.Session
	}
	return ""
}

func (m *LoginAsResp) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *LoginAsResp) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func init() {
	proto.RegisterType((*Dummy)(nil), "api.themakers.identity.Dummy")
	proto.RegisterType((*ProviderDetailsReq)(nil), "api.themakers.identity.ProviderDetailsReq")
	proto.RegisterType((*ProviderDetailsResp)(nil), "api.themakers.identity.ProviderDetailsResp")
	proto.RegisterType((*ProviderDetails)(nil), "api.themakers.identity.ProviderDetails")
	proto.RegisterType((*Type1VerificationReq)(nil), "api.themakers.identity.Type1VerificationReq")
	proto.RegisterType((*Type1VerificationDirections)(nil), "api.themakers.identity.Type1VerificationDirections")
	proto.RegisterType((*Type1ResultRequest)(nil), "api.themakers.identity.Type1ResultRequest")
	proto.RegisterType((*Type1ResultResp)(nil), "api.themakers.identity.Type1ResultResp")
	proto.RegisterType((*Type2VerificationReq)(nil), "api.themakers.identity.Type2VerificationReq")
	proto.RegisterType((*Type2VerificationResp)(nil), "api.themakers.identity.Type2VerificationResp")
	proto.RegisterType((*Type2VerifyReq)(nil), "api.themakers.identity.Type2VerifyReq")
	proto.RegisterType((*Type2ResultResp)(nil), "api.themakers.identity.Type2ResultResp")
	proto.RegisterType((*OAuth2Req)(nil), "api.themakers.identity.OAuth2Req")
	proto.RegisterType((*OAuth2VerifyResp)(nil), "api.themakers.identity.OAuth2VerifyResp")
	proto.RegisterType((*LoginAsReq)(nil), "api.themakers.identity.LoginAsReq")
	proto.RegisterType((*LoginAsResp)(nil), "api.themakers.identity.LoginAsResp")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// IdentityClient is the client API for Identity service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type IdentityClient interface {
	ListProviders(ctx context.Context, in *ProviderDetailsReq, opts ...grpc.CallOption) (*ProviderDetailsResp, error)
	// Type 1
	Type1Request(ctx context.Context, in *Type1VerificationReq, opts ...grpc.CallOption) (*Type1VerificationDirections, error)
	Type1Result(ctx context.Context, in *Type1ResultRequest, opts ...grpc.CallOption) (*Type1ResultResp, error)
	// Type 2
	Type2Request(ctx context.Context, in *Type2VerificationReq, opts ...grpc.CallOption) (*Type2VerificationResp, error)
	Type2Verify(ctx context.Context, in *Type2VerifyReq, opts ...grpc.CallOption) (*Type2ResultResp, error)
	// Type 3
	OAuth2Verify(ctx context.Context, in *OAuth2Req, opts ...grpc.CallOption) (*OAuth2VerifyResp, error)
}

type identityClient struct {
	cc *grpc.ClientConn
}

func NewIdentityClient(cc *grpc.ClientConn) IdentityClient {
	return &identityClient{cc}
}

func (c *identityClient) ListProviders(ctx context.Context, in *ProviderDetailsReq, opts ...grpc.CallOption) (*ProviderDetailsResp, error) {
	out := new(ProviderDetailsResp)
	err := c.cc.Invoke(ctx, "/api.themakers.identity.Identity/ListProviders", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityClient) Type1Request(ctx context.Context, in *Type1VerificationReq, opts ...grpc.CallOption) (*Type1VerificationDirections, error) {
	out := new(Type1VerificationDirections)
	err := c.cc.Invoke(ctx, "/api.themakers.identity.Identity/Type1Request", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityClient) Type1Result(ctx context.Context, in *Type1ResultRequest, opts ...grpc.CallOption) (*Type1ResultResp, error) {
	out := new(Type1ResultResp)
	err := c.cc.Invoke(ctx, "/api.themakers.identity.Identity/Type1Result", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityClient) Type2Request(ctx context.Context, in *Type2VerificationReq, opts ...grpc.CallOption) (*Type2VerificationResp, error) {
	out := new(Type2VerificationResp)
	err := c.cc.Invoke(ctx, "/api.themakers.identity.Identity/Type2Request", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityClient) Type2Verify(ctx context.Context, in *Type2VerifyReq, opts ...grpc.CallOption) (*Type2ResultResp, error) {
	out := new(Type2ResultResp)
	err := c.cc.Invoke(ctx, "/api.themakers.identity.Identity/Type2Verify", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityClient) OAuth2Verify(ctx context.Context, in *OAuth2Req, opts ...grpc.CallOption) (*OAuth2VerifyResp, error) {
	out := new(OAuth2VerifyResp)
	err := c.cc.Invoke(ctx, "/api.themakers.identity.Identity/OAuth2Verify", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IdentityServer is the server API for Identity service.
type IdentityServer interface {
	ListProviders(context.Context, *ProviderDetailsReq) (*ProviderDetailsResp, error)
	// Type 1
	Type1Request(context.Context, *Type1VerificationReq) (*Type1VerificationDirections, error)
	Type1Result(context.Context, *Type1ResultRequest) (*Type1ResultResp, error)
	// Type 2
	Type2Request(context.Context, *Type2VerificationReq) (*Type2VerificationResp, error)
	Type2Verify(context.Context, *Type2VerifyReq) (*Type2ResultResp, error)
	// Type 3
	OAuth2Verify(context.Context, *OAuth2Req) (*OAuth2VerifyResp, error)
}

func RegisterIdentityServer(s *grpc.Server, srv IdentityServer) {
	s.RegisterService(&_Identity_serviceDesc, srv)
}

func _Identity_ListProviders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProviderDetailsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServer).ListProviders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.themakers.identity.Identity/ListProviders",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServer).ListProviders(ctx, req.(*ProviderDetailsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Identity_Type1Request_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Type1VerificationReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServer).Type1Request(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.themakers.identity.Identity/Type1Request",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServer).Type1Request(ctx, req.(*Type1VerificationReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Identity_Type1Result_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Type1ResultRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServer).Type1Result(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.themakers.identity.Identity/Type1Result",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServer).Type1Result(ctx, req.(*Type1ResultRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Identity_Type2Request_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Type2VerificationReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServer).Type2Request(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.themakers.identity.Identity/Type2Request",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServer).Type2Request(ctx, req.(*Type2VerificationReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Identity_Type2Verify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Type2VerifyReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServer).Type2Verify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.themakers.identity.Identity/Type2Verify",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServer).Type2Verify(ctx, req.(*Type2VerifyReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Identity_OAuth2Verify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OAuth2Req)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServer).OAuth2Verify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.themakers.identity.Identity/OAuth2Verify",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServer).OAuth2Verify(ctx, req.(*OAuth2Req))
	}
	return interceptor(ctx, in, info, handler)
}

var _Identity_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.themakers.identity.Identity",
	HandlerType: (*IdentityServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListProviders",
			Handler:    _Identity_ListProviders_Handler,
		},
		{
			MethodName: "Type1Request",
			Handler:    _Identity_Type1Request_Handler,
		},
		{
			MethodName: "Type1Result",
			Handler:    _Identity_Type1Result_Handler,
		},
		{
			MethodName: "Type2Request",
			Handler:    _Identity_Type2Request_Handler,
		},
		{
			MethodName: "Type2Verify",
			Handler:    _Identity_Type2Verify_Handler,
		},
		{
			MethodName: "OAuth2Verify",
			Handler:    _Identity_OAuth2Verify_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "identity.proto",
}

// IdentityPrivateClient is the client API for IdentityPrivate service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type IdentityPrivateClient interface {
	LoginAs(ctx context.Context, in *LoginAsReq, opts ...grpc.CallOption) (*LoginAsResp, error)
}

type identityPrivateClient struct {
	cc *grpc.ClientConn
}

func NewIdentityPrivateClient(cc *grpc.ClientConn) IdentityPrivateClient {
	return &identityPrivateClient{cc}
}

func (c *identityPrivateClient) LoginAs(ctx context.Context, in *LoginAsReq, opts ...grpc.CallOption) (*LoginAsResp, error) {
	out := new(LoginAsResp)
	err := c.cc.Invoke(ctx, "/api.themakers.identity.IdentityPrivate/LoginAs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IdentityPrivateServer is the server API for IdentityPrivate service.
type IdentityPrivateServer interface {
	LoginAs(context.Context, *LoginAsReq) (*LoginAsResp, error)
}

func RegisterIdentityPrivateServer(s *grpc.Server, srv IdentityPrivateServer) {
	s.RegisterService(&_IdentityPrivate_serviceDesc, srv)
}

func _IdentityPrivate_LoginAs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginAsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityPrivateServer).LoginAs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.themakers.identity.IdentityPrivate/LoginAs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityPrivateServer).LoginAs(ctx, req.(*LoginAsReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _IdentityPrivate_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.themakers.identity.IdentityPrivate",
	HandlerType: (*IdentityPrivateServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "LoginAs",
			Handler:    _IdentityPrivate_LoginAs_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "identity.proto",
}

func init() { proto.RegisterFile("identity.proto", fileDescriptor_identity_1b3b7dff4977fe50) }

var fileDescriptor_identity_1b3b7dff4977fe50 = []byte{
	// 585 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x55, 0x4b, 0x6f, 0xd3, 0x40,
	0x10, 0x96, 0x69, 0xda, 0x34, 0x93, 0x34, 0xa9, 0x86, 0x50, 0x59, 0xe6, 0x12, 0x16, 0xd4, 0x46,
	0x3c, 0x22, 0xe1, 0x1e, 0x41, 0x42, 0x85, 0xf4, 0x50, 0xa9, 0x2a, 0xc5, 0x7d, 0x1c, 0xa0, 0x02,
	0xb9, 0xc9, 0xd2, 0xac, 0xda, 0xc4, 0x9b, 0xdd, 0x75, 0xa5, 0x1c, 0xf9, 0x0d, 0xfc, 0x56, 0xee,
	0xc8, 0xeb, 0xb5, 0x9d, 0x67, 0xe3, 0x4a, 0x39, 0x79, 0x67, 0x76, 0x66, 0xf6, 0xfb, 0x76, 0xe7,
	0x1b, 0x43, 0x95, 0x75, 0xe9, 0x40, 0x31, 0x35, 0x6a, 0x71, 0x11, 0xa8, 0x00, 0x77, 0x7c, 0xce,
	0x5a, 0xaa, 0x47, 0xfb, 0xfe, 0x2d, 0x15, 0xb2, 0x95, 0xec, 0x92, 0x22, 0xac, 0xb7, 0xc3, 0x7e,
	0x7f, 0x44, 0xea, 0x80, 0xa7, 0x22, 0xb8, 0x67, 0x5d, 0x2a, 0xda, 0x54, 0xf9, 0xec, 0x4e, 0x7a,
	0x74, 0x48, 0xae, 0xe0, 0xe9, 0x8c, 0x57, 0x72, 0x3c, 0x84, 0x52, 0xe2, 0x96, 0xb6, 0xd5, 0x58,
	0x6b, 0x96, 0xdd, 0xbd, 0xd6, 0xfc, 0x13, 0x5a, 0xd3, 0xf9, 0x59, 0x26, 0xf9, 0x6b, 0x41, 0x6d,
	0x6a, 0x1b, 0x11, 0x0a, 0x27, 0x7e, 0x9f, 0xda, 0x56, 0xc3, 0x6a, 0x96, 0x3c, 0xbd, 0x46, 0x02,
	0x95, 0xb3, 0x90, 0xf3, 0x40, 0xa8, 0xf3, 0x11, 0xa7, 0xef, 0xed, 0x27, 0x0d, 0xab, 0xb9, 0xe9,
	0x4d, 0xf8, 0xa6, 0x62, 0x5c, 0x7b, 0x6d, 0x26, 0xc6, 0xc5, 0x57, 0xb0, 0x65, 0xec, 0xaf, 0x07,
	0xa1, 0xea, 0xb9, 0x76, 0x41, 0x07, 0x4d, 0x3a, 0xc9, 0x09, 0xd4, 0x75, 0xc9, 0x4b, 0x2a, 0xd8,
	0x6f, 0xd6, 0xf1, 0x15, 0x0b, 0x06, 0x1e, 0x1d, 0xa2, 0x03, 0x9b, 0x09, 0x58, 0x83, 0x2e, 0xb5,
	0xa3, 0xbd, 0x23, 0x43, 0x58, 0xa3, 0x2b, 0x79, 0xa9, 0x4d, 0xfe, 0x58, 0xf0, 0x7c, 0xa6, 0x60,
	0x9b, 0x09, 0xda, 0x89, 0x16, 0x12, 0x77, 0xa1, 0x3a, 0xbe, 0x73, 0xd4, 0x36, 0xd5, 0xa7, 0xbc,
	0xb8, 0x03, 0x1b, 0xe7, 0xbe, 0xb8, 0xa1, 0xca, 0x9c, 0x60, 0x2c, 0xcd, 0x9c, 0x76, 0x42, 0xc1,
	0xd4, 0xe8, 0x4b, 0xd0, 0xa5, 0x9a, 0x79, 0xc9, 0x9b, 0xf0, 0x91, 0x8f, 0x80, 0x1a, 0x82, 0x47,
	0x65, 0x78, 0xa7, 0x3c, 0x3a, 0x0c, 0xa9, 0x54, 0x79, 0x4f, 0x26, 0x17, 0x50, 0x9b, 0xc8, 0x96,
	0x1c, 0x6d, 0x28, 0x9e, 0x51, 0x29, 0x59, 0x30, 0x30, 0x39, 0x89, 0x19, 0x3d, 0xe0, 0x85, 0xa4,
	0xc2, 0x80, 0xd4, 0x6b, 0xac, 0xc3, 0xfa, 0xa1, 0x10, 0x81, 0x30, 0xd8, 0x62, 0x23, 0xb9, 0x68,
	0x77, 0x55, 0x17, 0xfd, 0x09, 0x9e, 0xcd, 0xa9, 0x27, 0x79, 0x6e, 0x9e, 0x57, 0x50, 0xcd, 0x0a,
	0x8c, 0x22, 0x28, 0x79, 0xdf, 0x26, 0xcf, 0x1b, 0x98, 0x5b, 0x74, 0x57, 0x7c, 0x8b, 0x1f, 0xa0,
	0x14, 0x37, 0xee, 0xb2, 0xab, 0x43, 0x28, 0x68, 0x6c, 0xa6, 0xa4, 0xc6, 0x74, 0x09, 0xdb, 0x71,
	0x72, 0x42, 0x79, 0x45, 0xa0, 0x1a, 0x00, 0xc7, 0xc1, 0x0d, 0x1b, 0x1c, 0x44, 0x53, 0x24, 0xcd,
	0xb3, 0xb2, 0x3c, 0xf2, 0x0d, 0xca, 0x69, 0xc4, 0x6a, 0x0e, 0x75, 0xff, 0x15, 0xb2, 0xe6, 0xc0,
	0x1e, 0x6c, 0x1d, 0x33, 0xa9, 0xd2, 0x61, 0x83, 0xaf, 0xf3, 0x0e, 0x28, 0x3a, 0x74, 0xde, 0xe4,
	0x8e, 0x95, 0x1c, 0x87, 0x50, 0x31, 0xea, 0x88, 0x55, 0xf5, 0x76, 0x51, 0xf2, 0xbc, 0xa9, 0xe2,
	0xec, 0xe7, 0x8e, 0x1e, 0x1b, 0x19, 0xd7, 0x50, 0x1e, 0x13, 0xe4, 0x62, 0x6a, 0xb3, 0x9a, 0x77,
	0xf6, 0x72, 0xc5, 0x4a, 0x8e, 0xb7, 0x31, 0x2d, 0x37, 0x17, 0xad, 0x69, 0x0d, 0x3b, 0xef, 0x1e,
	0x11, 0x2d, 0x39, 0xfe, 0x8c, 0x09, 0x99, 0x36, 0xc4, 0xdd, 0xe5, 0xd9, 0x91, 0x3c, 0x1f, 0x26,
	0x33, 0x2e, 0xb4, 0x1f, 0x50, 0x19, 0xef, 0x73, 0x7c, 0xb1, 0x28, 0x31, 0x95, 0x92, 0xd3, 0x7c,
	0x38, 0x24, 0x13, 0x8c, 0x4b, 0xa1, 0x96, 0xb4, 0xdd, 0xa9, 0x60, 0xf7, 0xbe, 0xa2, 0xe8, 0x41,
	0xd1, 0x74, 0x37, 0x92, 0x45, 0x75, 0x32, 0x81, 0x38, 0x2f, 0x97, 0xc6, 0x48, 0xfe, 0x79, 0xfb,
	0x7b, 0xfa, 0x53, 0xff, 0xa5, 0x7f, 0xea, 0xd7, 0x1b, 0xfa, 0xb3, 0xff, 0x3f, 0x00, 0x00, 0xff,
	0xff, 0xb3, 0x4f, 0xbd, 0x59, 0xed, 0x07, 0x00, 0x00,
}
